/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter ts_nocheck,eslint_disable,long_type_string
// @generated from protobuf file "admin/admin.proto" (package "api.admin", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AdminService } from "./admin";
import type { GetStatsResp } from "./admin";
import type { GetStatsReq } from "./admin";
import type { AdminPositionDetailResp } from "./admin";
import type { GetPositionDetailReq } from "./admin";
import type { ListAllPositionsReq } from "./admin";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AdminPositionListResp } from "./admin";
import type { ListTodayPositionsReq } from "./admin";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * AdminService — admin dashboard queries, separate from AI-facing APIs
 *
 * @generated from protobuf service api.admin.AdminService
 */
export interface IAdminServiceClient {
    /**
     * Today's positions — most important for the admin to see progress
     *
     * @generated from protobuf rpc: ListTodayPositions
     */
    listTodayPositions(input: ListTodayPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListTodayPositionsReq, AdminPositionListResp>;
    /**
     * All positions with pagination and status filter
     *
     * @generated from protobuf rpc: ListAllPositions
     */
    listAllPositions(input: ListAllPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListAllPositionsReq, AdminPositionListResp>;
    /**
     * Position detail with match items and communications
     *
     * @generated from protobuf rpc: GetPositionDetail
     */
    getPositionDetail(input: GetPositionDetailReq, options?: RpcOptions): GrpcToHttpPromise<GetPositionDetailReq, AdminPositionDetailResp>;
    /**
     * Stats overview — count by status
     *
     * @generated from protobuf rpc: GetStats
     */
    getStats(input: GetStatsReq, options?: RpcOptions): GrpcToHttpPromise<GetStatsReq, GetStatsResp>;
}
/**
 * AdminService — admin dashboard queries, separate from AI-facing APIs
 *
 * @generated from protobuf service api.admin.AdminService
 */
export class AdminServiceClient implements IAdminServiceClient, ServiceInfo {
    typeName = AdminService.typeName;
    methods = AdminService.methods;
    options = AdminService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Today's positions — most important for the admin to see progress
     *
     * @generated from protobuf rpc: ListTodayPositions
     */
    listTodayPositions(input: ListTodayPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListTodayPositionsReq, AdminPositionListResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListTodayPositionsReq, AdminPositionListResp>("unary", this._transport, method, opt, input);
    }
    /**
     * All positions with pagination and status filter
     *
     * @generated from protobuf rpc: ListAllPositions
     */
    listAllPositions(input: ListAllPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListAllPositionsReq, AdminPositionListResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListAllPositionsReq, AdminPositionListResp>("unary", this._transport, method, opt, input);
    }
    /**
     * Position detail with match items and communications
     *
     * @generated from protobuf rpc: GetPositionDetail
     */
    getPositionDetail(input: GetPositionDetailReq, options?: RpcOptions): GrpcToHttpPromise<GetPositionDetailReq, AdminPositionDetailResp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<GetPositionDetailReq, AdminPositionDetailResp>("unary", this._transport, method, opt, input);
    }
    /**
     * Stats overview — count by status
     *
     * @generated from protobuf rpc: GetStats
     */
    getStats(input: GetStatsReq, options?: RpcOptions): GrpcToHttpPromise<GetStatsReq, GetStatsResp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<GetStatsReq, GetStatsResp>("unary", this._transport, method, opt, input);
    }
}
