// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "api/zhipin/blacklist.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BlacklistService } from "./blacklist";
import type { RemoveBlacklistResp } from "./blacklist";
import type { RemoveBlacklistReq } from "./blacklist";
import type { ListBlacklistResp } from "./blacklist";
import type { ListBlacklistReq } from "./blacklist";
import type { CheckBlacklistResp } from "./blacklist";
import type { CheckBlacklistReq } from "./blacklist";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BlacklistResp } from "./blacklist";
import type { AddBlacklistReq } from "./blacklist";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * BlacklistService — company blacklist management
 *
 * @generated from protobuf service api.zhipin.BlacklistService
 */
export interface IBlacklistServiceClient {
    /**
     * @generated from protobuf rpc: AddBlacklist
     */
    addBlacklist(input: AddBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<AddBlacklistReq, BlacklistResp>;
    /**
     * @generated from protobuf rpc: CheckBlacklist
     */
    checkBlacklist(input: CheckBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<CheckBlacklistReq, CheckBlacklistResp>;
    /**
     * @generated from protobuf rpc: ListBlacklist
     */
    listBlacklist(input: ListBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<ListBlacklistReq, ListBlacklistResp>;
    /**
     * @generated from protobuf rpc: RemoveBlacklist
     */
    removeBlacklist(input: RemoveBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<RemoveBlacklistReq, RemoveBlacklistResp>;
}
/**
 * BlacklistService — company blacklist management
 *
 * @generated from protobuf service api.zhipin.BlacklistService
 */
export class BlacklistServiceClient implements IBlacklistServiceClient, ServiceInfo {
    typeName = BlacklistService.typeName;
    methods = BlacklistService.methods;
    options = BlacklistService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AddBlacklist
     */
    addBlacklist(input: AddBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<AddBlacklistReq, BlacklistResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<AddBlacklistReq, BlacklistResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CheckBlacklist
     */
    checkBlacklist(input: CheckBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<CheckBlacklistReq, CheckBlacklistResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<CheckBlacklistReq, CheckBlacklistResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListBlacklist
     */
    listBlacklist(input: ListBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<ListBlacklistReq, ListBlacklistResp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListBlacklistReq, ListBlacklistResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveBlacklist
     */
    removeBlacklist(input: RemoveBlacklistReq, options?: RpcOptions): GrpcToHttpPromise<RemoveBlacklistReq, RemoveBlacklistResp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<RemoveBlacklistReq, RemoveBlacklistResp>("unary", this._transport, method, opt, input);
    }
}
