// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "api/zhipin/communication.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../google/protobuf/timestamp";
/**
 * @generated from protobuf message api.zhipin.RecordMsgSentReq
 */
export interface RecordMsgSentReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
}
/**
 * @generated from protobuf message api.zhipin.RecordMsgReceivedReq
 */
export interface RecordMsgReceivedReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
}
/**
 * @generated from protobuf message api.zhipin.RecordResumeSentReq
 */
export interface RecordResumeSentReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
    /**
     * @generated from protobuf field: string resume_version = 2
     */
    resumeVersion: string;
}
/**
 * @generated from protobuf message api.zhipin.RecordChatLimitedReq
 */
export interface RecordChatLimitedReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
}
/**
 * @generated from protobuf message api.zhipin.RecordInterviewReq
 */
export interface RecordInterviewReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp interview_time = 2
     */
    interviewTime?: Timestamp;
    /**
     * @generated from protobuf field: string notes = 3
     */
    notes: string;
}
/**
 * @generated from protobuf message api.zhipin.RecordRejectionReq
 */
export interface RecordRejectionReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string;
}
/**
 * @generated from protobuf message api.zhipin.ListCommunicationsReq
 */
export interface ListCommunicationsReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
}
/**
 * @generated from protobuf message api.zhipin.CommunicationResp
 */
export interface CommunicationResp {
    /**
     * @generated from protobuf field: uint64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: uint64 position_id = 2
     */
    positionId: string;
    /**
     * @generated from protobuf field: int32 event_type = 3
     */
    eventType: number;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp event_time = 4
     */
    eventTime?: Timestamp;
    /**
     * @generated from protobuf field: string content = 5
     */
    content: string;
    /**
     * @generated from protobuf field: int32 direction = 6
     */
    direction: number;
}
/**
 * @generated from protobuf message api.zhipin.ListCommunicationsResp
 */
export interface ListCommunicationsResp {
    /**
     * @generated from protobuf field: repeated api.zhipin.CommunicationResp items = 1
     */
    items: CommunicationResp[];
}
/**
 * @generated from protobuf enum api.zhipin.EventType
 */
export enum EventType {
    /**
     * @generated from protobuf enum value: EVENT_TYPE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: EVENT_TYPE_MSG_SENT = 1;
     */
    MSG_SENT = 1,
    /**
     * @generated from protobuf enum value: EVENT_TYPE_MSG_RECEIVED = 2;
     */
    MSG_RECEIVED = 2,
    /**
     * @generated from protobuf enum value: EVENT_TYPE_RESUME_SENT = 3;
     */
    RESUME_SENT = 3,
    /**
     * @generated from protobuf enum value: EVENT_TYPE_CHAT_LIMITED = 4;
     */
    CHAT_LIMITED = 4,
    /**
     * @generated from protobuf enum value: EVENT_TYPE_INTERVIEW = 5;
     */
    INTERVIEW = 5,
    /**
     * @generated from protobuf enum value: EVENT_TYPE_OFFER = 6;
     */
    OFFER = 6,
    /**
     * @generated from protobuf enum value: EVENT_TYPE_REJECTED = 7;
     */
    REJECTED = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class RecordMsgSentReq$Type extends MessageType<RecordMsgSentReq> {
    constructor() {
        super("api.zhipin.RecordMsgSentReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RecordMsgSentReq>): RecordMsgSentReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        message.content = "";
        if (value !== undefined)
            reflectionMergePartial<RecordMsgSentReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordMsgSentReq): RecordMsgSentReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordMsgSentReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RecordMsgSentReq
 */
export const RecordMsgSentReq = new RecordMsgSentReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordMsgReceivedReq$Type extends MessageType<RecordMsgReceivedReq> {
    constructor() {
        super("api.zhipin.RecordMsgReceivedReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RecordMsgReceivedReq>): RecordMsgReceivedReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        message.content = "";
        if (value !== undefined)
            reflectionMergePartial<RecordMsgReceivedReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordMsgReceivedReq): RecordMsgReceivedReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordMsgReceivedReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RecordMsgReceivedReq
 */
export const RecordMsgReceivedReq = new RecordMsgReceivedReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordResumeSentReq$Type extends MessageType<RecordResumeSentReq> {
    constructor() {
        super("api.zhipin.RecordResumeSentReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "resume_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RecordResumeSentReq>): RecordResumeSentReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        message.resumeVersion = "";
        if (value !== undefined)
            reflectionMergePartial<RecordResumeSentReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordResumeSentReq): RecordResumeSentReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* string resume_version */ 2:
                    message.resumeVersion = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordResumeSentReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        /* string resume_version = 2; */
        if (message.resumeVersion !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.resumeVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RecordResumeSentReq
 */
export const RecordResumeSentReq = new RecordResumeSentReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordChatLimitedReq$Type extends MessageType<RecordChatLimitedReq> {
    constructor() {
        super("api.zhipin.RecordChatLimitedReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<RecordChatLimitedReq>): RecordChatLimitedReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        if (value !== undefined)
            reflectionMergePartial<RecordChatLimitedReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordChatLimitedReq): RecordChatLimitedReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordChatLimitedReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RecordChatLimitedReq
 */
export const RecordChatLimitedReq = new RecordChatLimitedReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordInterviewReq$Type extends MessageType<RecordInterviewReq> {
    constructor() {
        super("api.zhipin.RecordInterviewReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "interview_time", kind: "message", T: () => Timestamp },
            { no: 3, name: "notes", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RecordInterviewReq>): RecordInterviewReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        message.notes = "";
        if (value !== undefined)
            reflectionMergePartial<RecordInterviewReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordInterviewReq): RecordInterviewReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* google.protobuf.Timestamp interview_time */ 2:
                    message.interviewTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.interviewTime);
                    break;
                case /* string notes */ 3:
                    message.notes = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordInterviewReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        /* google.protobuf.Timestamp interview_time = 2; */
        if (message.interviewTime)
            Timestamp.internalBinaryWrite(message.interviewTime, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string notes = 3; */
        if (message.notes !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.notes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RecordInterviewReq
 */
export const RecordInterviewReq = new RecordInterviewReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RecordRejectionReq$Type extends MessageType<RecordRejectionReq> {
    constructor() {
        super("api.zhipin.RecordRejectionReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RecordRejectionReq>): RecordRejectionReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        message.content = "";
        if (value !== undefined)
            reflectionMergePartial<RecordRejectionReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RecordRejectionReq): RecordRejectionReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RecordRejectionReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RecordRejectionReq
 */
export const RecordRejectionReq = new RecordRejectionReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListCommunicationsReq$Type extends MessageType<ListCommunicationsReq> {
    constructor() {
        super("api.zhipin.ListCommunicationsReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<ListCommunicationsReq>): ListCommunicationsReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        if (value !== undefined)
            reflectionMergePartial<ListCommunicationsReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListCommunicationsReq): ListCommunicationsReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListCommunicationsReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.ListCommunicationsReq
 */
export const ListCommunicationsReq = new ListCommunicationsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CommunicationResp$Type extends MessageType<CommunicationResp> {
    constructor() {
        super("api.zhipin.CommunicationResp", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 3, name: "event_type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "event_time", kind: "message", T: () => Timestamp },
            { no: 5, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "direction", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<CommunicationResp>): CommunicationResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        message.positionId = "0";
        message.eventType = 0;
        message.content = "";
        message.direction = 0;
        if (value !== undefined)
            reflectionMergePartial<CommunicationResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommunicationResp): CommunicationResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toString();
                    break;
                case /* uint64 position_id */ 2:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* int32 event_type */ 3:
                    message.eventType = reader.int32();
                    break;
                case /* google.protobuf.Timestamp event_time */ 4:
                    message.eventTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.eventTime);
                    break;
                case /* string content */ 5:
                    message.content = reader.string();
                    break;
                case /* int32 direction */ 6:
                    message.direction = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CommunicationResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* uint64 position_id = 2; */
        if (message.positionId !== "0")
            writer.tag(2, WireType.Varint).uint64(message.positionId);
        /* int32 event_type = 3; */
        if (message.eventType !== 0)
            writer.tag(3, WireType.Varint).int32(message.eventType);
        /* google.protobuf.Timestamp event_time = 4; */
        if (message.eventTime)
            Timestamp.internalBinaryWrite(message.eventTime, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string content = 5; */
        if (message.content !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.content);
        /* int32 direction = 6; */
        if (message.direction !== 0)
            writer.tag(6, WireType.Varint).int32(message.direction);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.CommunicationResp
 */
export const CommunicationResp = new CommunicationResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListCommunicationsResp$Type extends MessageType<ListCommunicationsResp> {
    constructor() {
        super("api.zhipin.ListCommunicationsResp", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CommunicationResp }
        ]);
    }
    create(value?: PartialMessage<ListCommunicationsResp>): ListCommunicationsResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<ListCommunicationsResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListCommunicationsResp): ListCommunicationsResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated api.zhipin.CommunicationResp items */ 1:
                    message.items.push(CommunicationResp.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListCommunicationsResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated api.zhipin.CommunicationResp items = 1; */
        for (let i = 0; i < message.items.length; i++)
            CommunicationResp.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.ListCommunicationsResp
 */
export const ListCommunicationsResp = new ListCommunicationsResp$Type();
/**
 * @generated ServiceType for protobuf service api.zhipin.CommunicationService
 */
export const CommunicationService = new ServiceType("api.zhipin.CommunicationService", [
    { name: "RecordMsgSent", options: { "google.api.http": { post: "/api/position/{position_id}/msg-sent", body: "*" } }, I: RecordMsgSentReq, O: CommunicationResp },
    { name: "RecordMsgReceived", options: { "google.api.http": { post: "/api/position/{position_id}/msg-received", body: "*" } }, I: RecordMsgReceivedReq, O: CommunicationResp },
    { name: "RecordResumeSent", options: { "google.api.http": { post: "/api/position/{position_id}/resume-sent", body: "*" } }, I: RecordResumeSentReq, O: CommunicationResp },
    { name: "RecordChatLimited", options: { "google.api.http": { post: "/api/position/{position_id}/chat-limited", body: "*" } }, I: RecordChatLimitedReq, O: CommunicationResp },
    { name: "RecordInterview", options: { "google.api.http": { post: "/api/position/{position_id}/interview", body: "*" } }, I: RecordInterviewReq, O: CommunicationResp },
    { name: "RecordRejection", options: { "google.api.http": { post: "/api/position/{position_id}/rejection", body: "*" } }, I: RecordRejectionReq, O: CommunicationResp },
    { name: "ListCommunications", options: { "google.api.http": { get: "/api/position/{position_id}/communications" } }, I: ListCommunicationsReq, O: ListCommunicationsResp }
]);
