// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "api/zhipin/match_item.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message api.zhipin.MatchItemInput
 */
export interface MatchItemInput {
    /**
     * @generated from protobuf field: string requirement = 1
     */
    requirement: string;
    /**
     * @generated from protobuf field: int32 match_status = 2
     */
    matchStatus: number;
    /**
     * @generated from protobuf field: string resume_point = 3
     */
    resumePoint: string;
    /**
     * @generated from protobuf field: string remark = 4
     */
    remark: string;
    /**
     * @generated from protobuf field: int32 sort_index = 5
     */
    sortIndex: number;
}
/**
 * @generated from protobuf message api.zhipin.SetMatchItemsReq
 */
export interface SetMatchItemsReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
    /**
     * @generated from protobuf field: repeated api.zhipin.MatchItemInput items = 2
     */
    items: MatchItemInput[];
}
/**
 * @generated from protobuf message api.zhipin.SetMatchItemsResp
 */
export interface SetMatchItemsResp {
    /**
     * @generated from protobuf field: int32 count = 1
     */
    count: number;
}
/**
 * @generated from protobuf message api.zhipin.ListMatchItemsReq
 */
export interface ListMatchItemsReq {
    /**
     * @generated from protobuf field: uint64 position_id = 1
     */
    positionId: string;
}
/**
 * @generated from protobuf message api.zhipin.MatchItemResp
 */
export interface MatchItemResp {
    /**
     * @generated from protobuf field: uint64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: uint64 position_id = 2
     */
    positionId: string;
    /**
     * @generated from protobuf field: string requirement = 3
     */
    requirement: string;
    /**
     * @generated from protobuf field: int32 match_status = 4
     */
    matchStatus: number;
    /**
     * @generated from protobuf field: string resume_point = 5
     */
    resumePoint: string;
    /**
     * @generated from protobuf field: string remark = 6
     */
    remark: string;
    /**
     * @generated from protobuf field: int32 sort_index = 7
     */
    sortIndex: number;
}
/**
 * @generated from protobuf message api.zhipin.ListMatchItemsResp
 */
export interface ListMatchItemsResp {
    /**
     * @generated from protobuf field: repeated api.zhipin.MatchItemResp items = 1
     */
    items: MatchItemResp[];
}
/**
 * @generated from protobuf enum api.zhipin.MatchStatus
 */
export enum MatchStatus {
    /**
     * @generated from protobuf enum value: MATCH_STATUS_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: MATCH_STATUS_MATCHED = 1;
     */
    MATCHED = 1,
    /**
     * @generated from protobuf enum value: MATCH_STATUS_PARTIAL = 2;
     */
    PARTIAL = 2,
    /**
     * @generated from protobuf enum value: MATCH_STATUS_MISSING = 3;
     */
    MISSING = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class MatchItemInput$Type extends MessageType<MatchItemInput> {
    constructor() {
        super("api.zhipin.MatchItemInput", [
            { no: 1, name: "requirement", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "match_status", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "resume_point", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "remark", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "sort_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<MatchItemInput>): MatchItemInput {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requirement = "";
        message.matchStatus = 0;
        message.resumePoint = "";
        message.remark = "";
        message.sortIndex = 0;
        if (value !== undefined)
            reflectionMergePartial<MatchItemInput>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MatchItemInput): MatchItemInput {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string requirement */ 1:
                    message.requirement = reader.string();
                    break;
                case /* int32 match_status */ 2:
                    message.matchStatus = reader.int32();
                    break;
                case /* string resume_point */ 3:
                    message.resumePoint = reader.string();
                    break;
                case /* string remark */ 4:
                    message.remark = reader.string();
                    break;
                case /* int32 sort_index */ 5:
                    message.sortIndex = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MatchItemInput, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string requirement = 1; */
        if (message.requirement !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requirement);
        /* int32 match_status = 2; */
        if (message.matchStatus !== 0)
            writer.tag(2, WireType.Varint).int32(message.matchStatus);
        /* string resume_point = 3; */
        if (message.resumePoint !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.resumePoint);
        /* string remark = 4; */
        if (message.remark !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.remark);
        /* int32 sort_index = 5; */
        if (message.sortIndex !== 0)
            writer.tag(5, WireType.Varint).int32(message.sortIndex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.MatchItemInput
 */
export const MatchItemInput = new MatchItemInput$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMatchItemsReq$Type extends MessageType<SetMatchItemsReq> {
    constructor() {
        super("api.zhipin.SetMatchItemsReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MatchItemInput }
        ]);
    }
    create(value?: PartialMessage<SetMatchItemsReq>): SetMatchItemsReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<SetMatchItemsReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetMatchItemsReq): SetMatchItemsReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* repeated api.zhipin.MatchItemInput items */ 2:
                    message.items.push(MatchItemInput.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetMatchItemsReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        /* repeated api.zhipin.MatchItemInput items = 2; */
        for (let i = 0; i < message.items.length; i++)
            MatchItemInput.internalBinaryWrite(message.items[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.SetMatchItemsReq
 */
export const SetMatchItemsReq = new SetMatchItemsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetMatchItemsResp$Type extends MessageType<SetMatchItemsResp> {
    constructor() {
        super("api.zhipin.SetMatchItemsResp", [
            { no: 1, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SetMatchItemsResp>): SetMatchItemsResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.count = 0;
        if (value !== undefined)
            reflectionMergePartial<SetMatchItemsResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetMatchItemsResp): SetMatchItemsResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 count */ 1:
                    message.count = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetMatchItemsResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 count = 1; */
        if (message.count !== 0)
            writer.tag(1, WireType.Varint).int32(message.count);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.SetMatchItemsResp
 */
export const SetMatchItemsResp = new SetMatchItemsResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMatchItemsReq$Type extends MessageType<ListMatchItemsReq> {
    constructor() {
        super("api.zhipin.ListMatchItemsReq", [
            { no: 1, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<ListMatchItemsReq>): ListMatchItemsReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.positionId = "0";
        if (value !== undefined)
            reflectionMergePartial<ListMatchItemsReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListMatchItemsReq): ListMatchItemsReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 position_id */ 1:
                    message.positionId = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListMatchItemsReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 position_id = 1; */
        if (message.positionId !== "0")
            writer.tag(1, WireType.Varint).uint64(message.positionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.ListMatchItemsReq
 */
export const ListMatchItemsReq = new ListMatchItemsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MatchItemResp$Type extends MessageType<MatchItemResp> {
    constructor() {
        super("api.zhipin.MatchItemResp", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "position_id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 3, name: "requirement", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "match_status", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "resume_point", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "remark", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "sort_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<MatchItemResp>): MatchItemResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        message.positionId = "0";
        message.requirement = "";
        message.matchStatus = 0;
        message.resumePoint = "";
        message.remark = "";
        message.sortIndex = 0;
        if (value !== undefined)
            reflectionMergePartial<MatchItemResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MatchItemResp): MatchItemResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toString();
                    break;
                case /* uint64 position_id */ 2:
                    message.positionId = reader.uint64().toString();
                    break;
                case /* string requirement */ 3:
                    message.requirement = reader.string();
                    break;
                case /* int32 match_status */ 4:
                    message.matchStatus = reader.int32();
                    break;
                case /* string resume_point */ 5:
                    message.resumePoint = reader.string();
                    break;
                case /* string remark */ 6:
                    message.remark = reader.string();
                    break;
                case /* int32 sort_index */ 7:
                    message.sortIndex = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MatchItemResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* uint64 position_id = 2; */
        if (message.positionId !== "0")
            writer.tag(2, WireType.Varint).uint64(message.positionId);
        /* string requirement = 3; */
        if (message.requirement !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.requirement);
        /* int32 match_status = 4; */
        if (message.matchStatus !== 0)
            writer.tag(4, WireType.Varint).int32(message.matchStatus);
        /* string resume_point = 5; */
        if (message.resumePoint !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.resumePoint);
        /* string remark = 6; */
        if (message.remark !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.remark);
        /* int32 sort_index = 7; */
        if (message.sortIndex !== 0)
            writer.tag(7, WireType.Varint).int32(message.sortIndex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.MatchItemResp
 */
export const MatchItemResp = new MatchItemResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListMatchItemsResp$Type extends MessageType<ListMatchItemsResp> {
    constructor() {
        super("api.zhipin.ListMatchItemsResp", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MatchItemResp }
        ]);
    }
    create(value?: PartialMessage<ListMatchItemsResp>): ListMatchItemsResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<ListMatchItemsResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListMatchItemsResp): ListMatchItemsResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated api.zhipin.MatchItemResp items */ 1:
                    message.items.push(MatchItemResp.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListMatchItemsResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated api.zhipin.MatchItemResp items = 1; */
        for (let i = 0; i < message.items.length; i++)
            MatchItemResp.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.ListMatchItemsResp
 */
export const ListMatchItemsResp = new ListMatchItemsResp$Type();
/**
 * @generated ServiceType for protobuf service api.zhipin.MatchItemService
 */
export const MatchItemService = new ServiceType("api.zhipin.MatchItemService", [
    { name: "SetMatchItems", options: { "google.api.http": { post: "/api/position/{position_id}/match-items", body: "*" } }, I: SetMatchItemsReq, O: SetMatchItemsResp },
    { name: "ListMatchItems", options: { "google.api.http": { get: "/api/position/{position_id}/match-items" } }, I: ListMatchItemsReq, O: ListMatchItemsResp }
]);
