// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "api/zhipin/reason_enum.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum api.zhipin.ErrorReason
 */
export enum ErrorReason {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: BAD_PARAM = 40000;
     */
    BAD_PARAM = 40000,
    /**
     * @generated from protobuf enum value: INVALID_JOB_ID = 40001;
     */
    INVALID_JOB_ID = 40001,
    /**
     * @generated from protobuf enum value: MISSING_FIELD = 40002;
     */
    MISSING_FIELD = 40002,
    /**
     * @generated from protobuf enum value: POSITION_NOT_FOUND = 40400;
     */
    POSITION_NOT_FOUND = 40400,
    /**
     * @generated from protobuf enum value: BLACKLIST_NOT_FOUND = 40401;
     */
    BLACKLIST_NOT_FOUND = 40401,
    /**
     * @generated from protobuf enum value: SERVER_ERROR = 50000;
     */
    SERVER_ERROR = 50000,
    /**
     * @generated from protobuf enum value: DB_ERROR = 50001;
     */
    DB_ERROR = 50001,
    /**
     * @generated from protobuf enum value: TX_ERROR = 50002;
     */
    TX_ERROR = 50002,
    /**
     * @generated from protobuf enum value: POSITION_CREATE_FAILURE = 50003;
     */
    POSITION_CREATE_FAILURE = 50003,
    /**
     * @generated from protobuf enum value: DUPLICATE_JOB_ID = 50004;
     */
    DUPLICATE_JOB_ID = 50004
}
