// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "api/zhipin/match_item.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MatchItemService } from "./requirement_item";
import type { ListMatchItemsResp } from "./requirement_item";
import type { ListMatchItemsReq } from "./requirement_item";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SetMatchItemsResp } from "./requirement_item";
import type { SetMatchItemsReq } from "./requirement_item";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * MatchItemService — per-requirement match analysis
 *
 * @generated from protobuf service api.zhipin.MatchItemService
 */
export interface IMatchItemServiceClient {
    /**
     * @generated from protobuf rpc: SetMatchItems
     */
    setMatchItems(input: SetMatchItemsReq, options?: RpcOptions): GrpcToHttpPromise<SetMatchItemsReq, SetMatchItemsResp>;
    /**
     * @generated from protobuf rpc: ListMatchItems
     */
    listMatchItems(input: ListMatchItemsReq, options?: RpcOptions): GrpcToHttpPromise<ListMatchItemsReq, ListMatchItemsResp>;
}
/**
 * MatchItemService — per-requirement match analysis
 *
 * @generated from protobuf service api.zhipin.MatchItemService
 */
export class MatchItemServiceClient implements IMatchItemServiceClient, ServiceInfo {
    typeName = MatchItemService.typeName;
    methods = MatchItemService.methods;
    options = MatchItemService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SetMatchItems
     */
    setMatchItems(input: SetMatchItemsReq, options?: RpcOptions): GrpcToHttpPromise<SetMatchItemsReq, SetMatchItemsResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<SetMatchItemsReq, SetMatchItemsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMatchItems
     */
    listMatchItems(input: ListMatchItemsReq, options?: RpcOptions): GrpcToHttpPromise<ListMatchItemsReq, ListMatchItemsResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListMatchItemsReq, ListMatchItemsResp>("unary", this._transport, method, opt, input);
    }
}
