// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/yylego/kratos-zap/zapkratos"
	"github.com/yylego/smart-employee-zhipin/zhipin-kratos/internal/biz"
	"github.com/yylego/smart-employee-zhipin/zhipin-kratos/internal/conf"
	"github.com/yylego/smart-employee-zhipin/zhipin-kratos/internal/data"
	"github.com/yylego/smart-employee-zhipin/zhipin-kratos/internal/server"
	"github.com/yylego/smart-employee-zhipin/zhipin-kratos/internal/service"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, zapKratos *zapkratos.ZapKratos) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, zapKratos)
	if err != nil {
		return nil, nil, err
	}
	uc岗位管理 := biz.NewUc岗位管理(dataData, zapKratos)
	uc需求匹配 := biz.NewUc需求匹配(dataData, zapKratos)
	svc岗位管理 := service.NewSvc岗位管理(uc岗位管理, uc需求匹配)
	uc沟通管理 := biz.NewUc沟通管理(dataData, zapKratos)
	svc沟通管理 := service.NewSvc沟通管理(uc沟通管理)
	svc需求匹配 := service.NewSvc需求匹配(uc需求匹配)
	uc黑名单管理 := biz.NewUc黑名单管理(dataData, zapKratos)
	svc黑名单管理 := service.NewSvc黑名单管理(uc黑名单管理)
	svc管理面板 := service.NewSvc管理面板(uc岗位管理, uc需求匹配, uc沟通管理)
	grpcServer := server.NewGRPCServer(confServer, svc岗位管理, svc沟通管理, svc需求匹配, svc黑名单管理, svc管理面板, zapKratos)
	httpServer := server.NewHTTPServer(confServer, svc岗位管理, svc沟通管理, svc需求匹配, svc黑名单管理, svc管理面板, zapKratos)
	app := newApp(grpcServer, httpServer, zapKratos)
	return app, func() {
		cleanup()
	}, nil
}
