// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: zhipin/blacklist.proto

package zhipin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlacklistReq) Reset() {
	*x = AddBlacklistReq{}
	mi := &file_zhipin_blacklist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistReq) ProtoMessage() {}

func (x *AddBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistReq.ProtoReflect.Descriptor instead.
func (*AddBlacklistReq) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{0}
}

func (x *AddBlacklistReq) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *AddBlacklistReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CheckBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Company       string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistReq) Reset() {
	*x = CheckBlacklistReq{}
	mi := &file_zhipin_blacklist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistReq) ProtoMessage() {}

func (x *CheckBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistReq.ProtoReflect.Descriptor instead.
func (*CheckBlacklistReq) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{1}
}

func (x *CheckBlacklistReq) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

type CheckBlacklistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blacklisted   bool                   `protobuf:"varint,1,opt,name=blacklisted,proto3" json:"blacklisted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistResp) Reset() {
	*x = CheckBlacklistResp{}
	mi := &file_zhipin_blacklist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistResp) ProtoMessage() {}

func (x *CheckBlacklistResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistResp.ProtoReflect.Descriptor instead.
func (*CheckBlacklistResp) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{2}
}

func (x *CheckBlacklistResp) GetBlacklisted() bool {
	if x != nil {
		return x.Blacklisted
	}
	return false
}

type ListBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistReq) Reset() {
	*x = ListBlacklistReq{}
	mi := &file_zhipin_blacklist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistReq) ProtoMessage() {}

func (x *ListBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistReq.ProtoReflect.Descriptor instead.
func (*ListBlacklistReq) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{3}
}

type BlacklistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistResp) Reset() {
	*x = BlacklistResp{}
	mi := &file_zhipin_blacklist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistResp) ProtoMessage() {}

func (x *BlacklistResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistResp.ProtoReflect.Descriptor instead.
func (*BlacklistResp) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{4}
}

func (x *BlacklistResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlacklistResp) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *BlacklistResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ListBlacklistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BlacklistResp       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistResp) Reset() {
	*x = ListBlacklistResp{}
	mi := &file_zhipin_blacklist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistResp) ProtoMessage() {}

func (x *ListBlacklistResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistResp.ProtoReflect.Descriptor instead.
func (*ListBlacklistResp) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{5}
}

func (x *ListBlacklistResp) GetItems() []*BlacklistResp {
	if x != nil {
		return x.Items
	}
	return nil
}

type RemoveBlacklistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistReq) Reset() {
	*x = RemoveBlacklistReq{}
	mi := &file_zhipin_blacklist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistReq) ProtoMessage() {}

func (x *RemoveBlacklistReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistReq.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistReq) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveBlacklistReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveBlacklistResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistResp) Reset() {
	*x = RemoveBlacklistResp{}
	mi := &file_zhipin_blacklist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistResp) ProtoMessage() {}

func (x *RemoveBlacklistResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_blacklist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistResp.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistResp) Descriptor() ([]byte, []int) {
	return file_zhipin_blacklist_proto_rawDescGZIP(), []int{7}
}

var File_zhipin_blacklist_proto protoreflect.FileDescriptor

const file_zhipin_blacklist_proto_rawDesc = "" +
	"\n" +
	"\x16zhipin/blacklist.proto\x12\n" +
	"api.zhipin\x1a\x1cgoogle/api/annotations.proto\"C\n" +
	"\x0fAddBlacklistReq\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"-\n" +
	"\x11CheckBlacklistReq\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\"6\n" +
	"\x12CheckBlacklistResp\x12 \n" +
	"\vblacklisted\x18\x01 \x01(\bR\vblacklisted\"\x12\n" +
	"\x10ListBlacklistReq\"Q\n" +
	"\rBlacklistResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"D\n" +
	"\x11ListBlacklistResp\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.api.zhipin.BlacklistRespR\x05items\"$\n" +
	"\x12RemoveBlacklistReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x15\n" +
	"\x13RemoveBlacklistResp2\xc5\x03\n" +
	"\x10BlacklistService\x12a\n" +
	"\fAddBlacklist\x12\x1b.api.zhipin.AddBlacklistReq\x1a\x19.api.zhipin.BlacklistResp\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/blacklist\x12w\n" +
	"\x0eCheckBlacklist\x12\x1d.api.zhipin.CheckBlacklistReq\x1a\x1e.api.zhipin.CheckBlacklistResp\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/blacklist/check/{company}\x12d\n" +
	"\rListBlacklist\x12\x1c.api.zhipin.ListBlacklistReq\x1a\x1d.api.zhipin.ListBlacklistResp\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/blacklist\x12o\n" +
	"\x0fRemoveBlacklist\x12\x1e.api.zhipin.RemoveBlacklistReq\x1a\x1f.api.zhipin.RemoveBlacklistResp\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/api/blacklist/{id}BIZGgithub.com/yylego/smart-employee-zhipin/zhipin-kratos/api/zhipin;zhipinb\x06proto3"

var (
	file_zhipin_blacklist_proto_rawDescOnce sync.Once
	file_zhipin_blacklist_proto_rawDescData []byte
)

func file_zhipin_blacklist_proto_rawDescGZIP() []byte {
	file_zhipin_blacklist_proto_rawDescOnce.Do(func() {
		file_zhipin_blacklist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhipin_blacklist_proto_rawDesc), len(file_zhipin_blacklist_proto_rawDesc)))
	})
	return file_zhipin_blacklist_proto_rawDescData
}

var file_zhipin_blacklist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zhipin_blacklist_proto_goTypes = []any{
	(*AddBlacklistReq)(nil),     // 0: api.zhipin.AddBlacklistReq
	(*CheckBlacklistReq)(nil),   // 1: api.zhipin.CheckBlacklistReq
	(*CheckBlacklistResp)(nil),  // 2: api.zhipin.CheckBlacklistResp
	(*ListBlacklistReq)(nil),    // 3: api.zhipin.ListBlacklistReq
	(*BlacklistResp)(nil),       // 4: api.zhipin.BlacklistResp
	(*ListBlacklistResp)(nil),   // 5: api.zhipin.ListBlacklistResp
	(*RemoveBlacklistReq)(nil),  // 6: api.zhipin.RemoveBlacklistReq
	(*RemoveBlacklistResp)(nil), // 7: api.zhipin.RemoveBlacklistResp
}
var file_zhipin_blacklist_proto_depIdxs = []int32{
	4, // 0: api.zhipin.ListBlacklistResp.items:type_name -> api.zhipin.BlacklistResp
	0, // 1: api.zhipin.BlacklistService.AddBlacklist:input_type -> api.zhipin.AddBlacklistReq
	1, // 2: api.zhipin.BlacklistService.CheckBlacklist:input_type -> api.zhipin.CheckBlacklistReq
	3, // 3: api.zhipin.BlacklistService.ListBlacklist:input_type -> api.zhipin.ListBlacklistReq
	6, // 4: api.zhipin.BlacklistService.RemoveBlacklist:input_type -> api.zhipin.RemoveBlacklistReq
	4, // 5: api.zhipin.BlacklistService.AddBlacklist:output_type -> api.zhipin.BlacklistResp
	2, // 6: api.zhipin.BlacklistService.CheckBlacklist:output_type -> api.zhipin.CheckBlacklistResp
	5, // 7: api.zhipin.BlacklistService.ListBlacklist:output_type -> api.zhipin.ListBlacklistResp
	7, // 8: api.zhipin.BlacklistService.RemoveBlacklist:output_type -> api.zhipin.RemoveBlacklistResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zhipin_blacklist_proto_init() }
func file_zhipin_blacklist_proto_init() {
	if File_zhipin_blacklist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhipin_blacklist_proto_rawDesc), len(file_zhipin_blacklist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhipin_blacklist_proto_goTypes,
		DependencyIndexes: file_zhipin_blacklist_proto_depIdxs,
		MessageInfos:      file_zhipin_blacklist_proto_msgTypes,
	}.Build()
	File_zhipin_blacklist_proto = out.File
	file_zhipin_blacklist_proto_goTypes = nil
	file_zhipin_blacklist_proto_depIdxs = nil
}
