// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: zhipin/blacklist.proto

package zhipin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlacklistService_AddBlacklist_FullMethodName    = "/api.zhipin.BlacklistService/AddBlacklist"
	BlacklistService_CheckBlacklist_FullMethodName  = "/api.zhipin.BlacklistService/CheckBlacklist"
	BlacklistService_ListBlacklist_FullMethodName   = "/api.zhipin.BlacklistService/ListBlacklist"
	BlacklistService_RemoveBlacklist_FullMethodName = "/api.zhipin.BlacklistService/RemoveBlacklist"
)

// BlacklistServiceClient is the client API for BlacklistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlacklistService — company blacklist management
type BlacklistServiceClient interface {
	AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*BlacklistResp, error)
	CheckBlacklist(ctx context.Context, in *CheckBlacklistReq, opts ...grpc.CallOption) (*CheckBlacklistResp, error)
	ListBlacklist(ctx context.Context, in *ListBlacklistReq, opts ...grpc.CallOption) (*ListBlacklistResp, error)
	RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*RemoveBlacklistResp, error)
}

type blacklistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlacklistServiceClient(cc grpc.ClientConnInterface) BlacklistServiceClient {
	return &blacklistServiceClient{cc}
}

func (c *blacklistServiceClient) AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*BlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlacklistResp)
	err := c.cc.Invoke(ctx, BlacklistService_AddBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blacklistServiceClient) CheckBlacklist(ctx context.Context, in *CheckBlacklistReq, opts ...grpc.CallOption) (*CheckBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBlacklistResp)
	err := c.cc.Invoke(ctx, BlacklistService_CheckBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blacklistServiceClient) ListBlacklist(ctx context.Context, in *ListBlacklistReq, opts ...grpc.CallOption) (*ListBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlacklistResp)
	err := c.cc.Invoke(ctx, BlacklistService_ListBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blacklistServiceClient) RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*RemoveBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBlacklistResp)
	err := c.cc.Invoke(ctx, BlacklistService_RemoveBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlacklistServiceServer is the server API for BlacklistService service.
// All implementations must embed UnimplementedBlacklistServiceServer
// for forward compatibility.
//
// BlacklistService — company blacklist management
type BlacklistServiceServer interface {
	AddBlacklist(context.Context, *AddBlacklistReq) (*BlacklistResp, error)
	CheckBlacklist(context.Context, *CheckBlacklistReq) (*CheckBlacklistResp, error)
	ListBlacklist(context.Context, *ListBlacklistReq) (*ListBlacklistResp, error)
	RemoveBlacklist(context.Context, *RemoveBlacklistReq) (*RemoveBlacklistResp, error)
	mustEmbedUnimplementedBlacklistServiceServer()
}

// UnimplementedBlacklistServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlacklistServiceServer struct{}

func (UnimplementedBlacklistServiceServer) AddBlacklist(context.Context, *AddBlacklistReq) (*BlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBlacklist not implemented")
}
func (UnimplementedBlacklistServiceServer) CheckBlacklist(context.Context, *CheckBlacklistReq) (*CheckBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBlacklist not implemented")
}
func (UnimplementedBlacklistServiceServer) ListBlacklist(context.Context, *ListBlacklistReq) (*ListBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlacklist not implemented")
}
func (UnimplementedBlacklistServiceServer) RemoveBlacklist(context.Context, *RemoveBlacklistReq) (*RemoveBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBlacklist not implemented")
}
func (UnimplementedBlacklistServiceServer) mustEmbedUnimplementedBlacklistServiceServer() {}
func (UnimplementedBlacklistServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlacklistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlacklistServiceServer will
// result in compilation errors.
type UnsafeBlacklistServiceServer interface {
	mustEmbedUnimplementedBlacklistServiceServer()
}

func RegisterBlacklistServiceServer(s grpc.ServiceRegistrar, srv BlacklistServiceServer) {
	// If the following call panics, it indicates UnimplementedBlacklistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlacklistService_ServiceDesc, srv)
}

func _BlacklistService_AddBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServiceServer).AddBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlacklistService_AddBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServiceServer).AddBlacklist(ctx, req.(*AddBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlacklistService_CheckBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServiceServer).CheckBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlacklistService_CheckBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServiceServer).CheckBlacklist(ctx, req.(*CheckBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlacklistService_ListBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServiceServer).ListBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlacklistService_ListBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServiceServer).ListBlacklist(ctx, req.(*ListBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlacklistService_RemoveBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlacklistServiceServer).RemoveBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlacklistService_RemoveBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlacklistServiceServer).RemoveBlacklist(ctx, req.(*RemoveBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BlacklistService_ServiceDesc is the grpc.ServiceDesc for BlacklistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlacklistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.zhipin.BlacklistService",
	HandlerType: (*BlacklistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlacklist",
			Handler:    _BlacklistService_AddBlacklist_Handler,
		},
		{
			MethodName: "CheckBlacklist",
			Handler:    _BlacklistService_CheckBlacklist_Handler,
		},
		{
			MethodName: "ListBlacklist",
			Handler:    _BlacklistService_ListBlacklist_Handler,
		},
		{
			MethodName: "RemoveBlacklist",
			Handler:    _BlacklistService_RemoveBlacklist_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhipin/blacklist.proto",
}
