// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: zhipin/communication.proto

package zhipin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     int32                  `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"`                             // 0=me 1=them
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                  // message text
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // unix seconds
	IsResume      bool                   `protobuf:"varint,4,opt,name=is_resume,json=isResume,proto3" json:"is_resume,omitempty"`               // is this a resume message
	ResumeVersion string                 `protobuf:"bytes,5,opt,name=resume_version,json=resumeVersion,proto3" json:"resume_version,omitempty"` // resume filename if is_resume=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_zhipin_communication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_communication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_zhipin_communication_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ChatMessage) GetIsResume() bool {
	if x != nil {
		return x.IsResume
	}
	return false
}

func (x *ChatMessage) GetResumeVersion() string {
	if x != nil {
		return x.ResumeVersion
	}
	return ""
}

type SyncChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChatReq) Reset() {
	*x = SyncChatReq{}
	mi := &file_zhipin_communication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChatReq) ProtoMessage() {}

func (x *SyncChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_communication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChatReq.ProtoReflect.Descriptor instead.
func (*SyncChatReq) Descriptor() ([]byte, []int) {
	return file_zhipin_communication_proto_rawDescGZIP(), []int{1}
}

func (x *SyncChatReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SyncChatReq) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SyncChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastCommAt    int64                  `protobuf:"varint,1,opt,name=last_comm_at,json=lastCommAt,proto3" json:"last_comm_at,omitempty"`    // extracted from messages
	LastCommDir   int32                  `protobuf:"varint,2,opt,name=last_comm_dir,json=lastCommDir,proto3" json:"last_comm_dir,omitempty"` // extracted from messages
	LastResume    string                 `protobuf:"bytes,3,opt,name=last_resume,json=lastResume,proto3" json:"last_resume,omitempty"`       // extracted from messages
	MessageCount  int32                  `protobuf:"varint,4,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncChatResp) Reset() {
	*x = SyncChatResp{}
	mi := &file_zhipin_communication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChatResp) ProtoMessage() {}

func (x *SyncChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_communication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChatResp.ProtoReflect.Descriptor instead.
func (*SyncChatResp) Descriptor() ([]byte, []int) {
	return file_zhipin_communication_proto_rawDescGZIP(), []int{2}
}

func (x *SyncChatResp) GetLastCommAt() int64 {
	if x != nil {
		return x.LastCommAt
	}
	return 0
}

func (x *SyncChatResp) GetLastCommDir() int32 {
	if x != nil {
		return x.LastCommDir
	}
	return 0
}

func (x *SyncChatResp) GetLastResume() string {
	if x != nil {
		return x.LastResume
	}
	return ""
}

func (x *SyncChatResp) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type GetChatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatReq) Reset() {
	*x = GetChatReq{}
	mi := &file_zhipin_communication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatReq) ProtoMessage() {}

func (x *GetChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_communication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatReq.ProtoReflect.Descriptor instead.
func (*GetChatReq) Descriptor() ([]byte, []int) {
	return file_zhipin_communication_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetChatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResp) Reset() {
	*x = GetChatResp{}
	mi := &file_zhipin_communication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResp) ProtoMessage() {}

func (x *GetChatResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_communication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResp.ProtoReflect.Descriptor instead.
func (*GetChatResp) Descriptor() ([]byte, []int) {
	return file_zhipin_communication_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatResp) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_zhipin_communication_proto protoreflect.FileDescriptor

const file_zhipin_communication_proto_rawDesc = "" +
	"\n" +
	"\x1azhipin/communication.proto\x12\n" +
	"api.zhipin\x1a\x1cgoogle/api/annotations.proto\"\xa7\x01\n" +
	"\vChatMessage\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\x05R\tdirection\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tis_resume\x18\x04 \x01(\bR\bisResume\x12%\n" +
	"\x0eresume_version\x18\x05 \x01(\tR\rresumeVersion\"Y\n" +
	"\vSyncChatReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x123\n" +
	"\bmessages\x18\x02 \x03(\v2\x17.api.zhipin.ChatMessageR\bmessages\"\x9a\x01\n" +
	"\fSyncChatResp\x12 \n" +
	"\flast_comm_at\x18\x01 \x01(\x03R\n" +
	"lastCommAt\x12\"\n" +
	"\rlast_comm_dir\x18\x02 \x01(\x05R\vlastCommDir\x12\x1f\n" +
	"\vlast_resume\x18\x03 \x01(\tR\n" +
	"lastResume\x12#\n" +
	"\rmessage_count\x18\x04 \x01(\x05R\fmessageCount\"#\n" +
	"\n" +
	"GetChatReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"B\n" +
	"\vGetChatResp\x123\n" +
	"\bmessages\x18\x01 \x03(\v2\x17.api.zhipin.ChatMessageR\bmessages2\xcc\x01\n" +
	"\x14CommunicationService\x12\\\n" +
	"\bSyncChat\x12\x17.api.zhipin.SyncChatReq\x1a\x18.api.zhipin.SyncChatResp\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/chat/{job_id}\x12V\n" +
	"\aGetChat\x12\x16.api.zhipin.GetChatReq\x1a\x17.api.zhipin.GetChatResp\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/chat/{job_id}BIZGgithub.com/yylego/smart-employee-zhipin/zhipin-kratos/api/zhipin;zhipinb\x06proto3"

var (
	file_zhipin_communication_proto_rawDescOnce sync.Once
	file_zhipin_communication_proto_rawDescData []byte
)

func file_zhipin_communication_proto_rawDescGZIP() []byte {
	file_zhipin_communication_proto_rawDescOnce.Do(func() {
		file_zhipin_communication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhipin_communication_proto_rawDesc), len(file_zhipin_communication_proto_rawDesc)))
	})
	return file_zhipin_communication_proto_rawDescData
}

var file_zhipin_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_zhipin_communication_proto_goTypes = []any{
	(*ChatMessage)(nil),  // 0: api.zhipin.ChatMessage
	(*SyncChatReq)(nil),  // 1: api.zhipin.SyncChatReq
	(*SyncChatResp)(nil), // 2: api.zhipin.SyncChatResp
	(*GetChatReq)(nil),   // 3: api.zhipin.GetChatReq
	(*GetChatResp)(nil),  // 4: api.zhipin.GetChatResp
}
var file_zhipin_communication_proto_depIdxs = []int32{
	0, // 0: api.zhipin.SyncChatReq.messages:type_name -> api.zhipin.ChatMessage
	0, // 1: api.zhipin.GetChatResp.messages:type_name -> api.zhipin.ChatMessage
	1, // 2: api.zhipin.CommunicationService.SyncChat:input_type -> api.zhipin.SyncChatReq
	3, // 3: api.zhipin.CommunicationService.GetChat:input_type -> api.zhipin.GetChatReq
	2, // 4: api.zhipin.CommunicationService.SyncChat:output_type -> api.zhipin.SyncChatResp
	4, // 5: api.zhipin.CommunicationService.GetChat:output_type -> api.zhipin.GetChatResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zhipin_communication_proto_init() }
func file_zhipin_communication_proto_init() {
	if File_zhipin_communication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhipin_communication_proto_rawDesc), len(file_zhipin_communication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhipin_communication_proto_goTypes,
		DependencyIndexes: file_zhipin_communication_proto_depIdxs,
		MessageInfos:      file_zhipin_communication_proto_msgTypes,
	}.Build()
	File_zhipin_communication_proto = out.File
	file_zhipin_communication_proto_goTypes = nil
	file_zhipin_communication_proto_depIdxs = nil
}
