// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: zhipin/communication.proto

package zhipin

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCommunicationServiceGetChat = "/api.zhipin.CommunicationService/GetChat"
const OperationCommunicationServiceSyncChat = "/api.zhipin.CommunicationService/SyncChat"

type CommunicationServiceHTTPServer interface {
	GetChat(context.Context, *GetChatReq) (*GetChatResp, error)
	SyncChat(context.Context, *SyncChatReq) (*SyncChatResp, error)
}

func RegisterCommunicationServiceHTTPServer(s *http.Server, srv CommunicationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/chat/{job_id}", _CommunicationService_SyncChat0_HTTP_Handler(srv))
	r.GET("/api/chat/{job_id}", _CommunicationService_GetChat0_HTTP_Handler(srv))
}

func _CommunicationService_SyncChat0_HTTP_Handler(srv CommunicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncChatReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommunicationServiceSyncChat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncChat(ctx, req.(*SyncChatReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncChatResp)
		return ctx.Result(200, reply)
	}
}

func _CommunicationService_GetChat0_HTTP_Handler(srv CommunicationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetChatReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCommunicationServiceGetChat)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChat(ctx, req.(*GetChatReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetChatResp)
		return ctx.Result(200, reply)
	}
}

type CommunicationServiceHTTPClient interface {
	GetChat(ctx context.Context, req *GetChatReq, opts ...http.CallOption) (rsp *GetChatResp, err error)
	SyncChat(ctx context.Context, req *SyncChatReq, opts ...http.CallOption) (rsp *SyncChatResp, err error)
}

type CommunicationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCommunicationServiceHTTPClient(client *http.Client) CommunicationServiceHTTPClient {
	return &CommunicationServiceHTTPClientImpl{client}
}

func (c *CommunicationServiceHTTPClientImpl) GetChat(ctx context.Context, in *GetChatReq, opts ...http.CallOption) (*GetChatResp, error) {
	var out GetChatResp
	pattern := "/api/chat/{job_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationCommunicationServiceGetChat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CommunicationServiceHTTPClientImpl) SyncChat(ctx context.Context, in *SyncChatReq, opts ...http.CallOption) (*SyncChatResp, error) {
	var out SyncChatResp
	pattern := "/api/chat/{job_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCommunicationServiceSyncChat))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
