// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: api/zhipin/match_item.proto

package zhipin

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMatchItemServiceListMatchItems = "/api.zhipin.MatchItemService/ListMatchItems"
const OperationMatchItemServiceSetMatchItems = "/api.zhipin.MatchItemService/SetMatchItems"

type MatchItemServiceHTTPServer interface {
	ListMatchItems(context.Context, *ListMatchItemsReq) (*ListMatchItemsResp, error)
	SetMatchItems(context.Context, *SetMatchItemsReq) (*SetMatchItemsResp, error)
}

func RegisterMatchItemServiceHTTPServer(s *http.Server, srv MatchItemServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/position/{position_id}/match-items", _MatchItemService_SetMatchItems0_HTTP_Handler(srv))
	r.GET("/api/position/{position_id}/match-items", _MatchItemService_ListMatchItems0_HTTP_Handler(srv))
}

func _MatchItemService_SetMatchItems0_HTTP_Handler(srv MatchItemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetMatchItemsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMatchItemServiceSetMatchItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetMatchItems(ctx, req.(*SetMatchItemsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetMatchItemsResp)
		return ctx.Result(200, reply)
	}
}

func _MatchItemService_ListMatchItems0_HTTP_Handler(srv MatchItemServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMatchItemsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMatchItemServiceListMatchItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMatchItems(ctx, req.(*ListMatchItemsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMatchItemsResp)
		return ctx.Result(200, reply)
	}
}

type MatchItemServiceHTTPClient interface {
	ListMatchItems(ctx context.Context, req *ListMatchItemsReq, opts ...http.CallOption) (rsp *ListMatchItemsResp, err error)
	SetMatchItems(ctx context.Context, req *SetMatchItemsReq, opts ...http.CallOption) (rsp *SetMatchItemsResp, err error)
}

type MatchItemServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMatchItemServiceHTTPClient(client *http.Client) MatchItemServiceHTTPClient {
	return &MatchItemServiceHTTPClientImpl{client}
}

func (c *MatchItemServiceHTTPClientImpl) ListMatchItems(ctx context.Context, in *ListMatchItemsReq, opts ...http.CallOption) (*ListMatchItemsResp, error) {
	var out ListMatchItemsResp
	pattern := "/api/position/{position_id}/match-items"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMatchItemServiceListMatchItems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MatchItemServiceHTTPClientImpl) SetMatchItems(ctx context.Context, in *SetMatchItemsReq, opts ...http.CallOption) (*SetMatchItemsResp, error) {
	var out SetMatchItemsResp
	pattern := "/api/position/{position_id}/match-items"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMatchItemServiceSetMatchItems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
