// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/zhipin/match_item.proto

package zhipin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchItemService_SetMatchItems_FullMethodName  = "/api.zhipin.MatchItemService/SetMatchItems"
	MatchItemService_ListMatchItems_FullMethodName = "/api.zhipin.MatchItemService/ListMatchItems"
)

// MatchItemServiceClient is the client API for MatchItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MatchItemService — per-requirement match analysis
type MatchItemServiceClient interface {
	SetMatchItems(ctx context.Context, in *SetMatchItemsReq, opts ...grpc.CallOption) (*SetMatchItemsResp, error)
	ListMatchItems(ctx context.Context, in *ListMatchItemsReq, opts ...grpc.CallOption) (*ListMatchItemsResp, error)
}

type matchItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchItemServiceClient(cc grpc.ClientConnInterface) MatchItemServiceClient {
	return &matchItemServiceClient{cc}
}

func (c *matchItemServiceClient) SetMatchItems(ctx context.Context, in *SetMatchItemsReq, opts ...grpc.CallOption) (*SetMatchItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMatchItemsResp)
	err := c.cc.Invoke(ctx, MatchItemService_SetMatchItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchItemServiceClient) ListMatchItems(ctx context.Context, in *ListMatchItemsReq, opts ...grpc.CallOption) (*ListMatchItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMatchItemsResp)
	err := c.cc.Invoke(ctx, MatchItemService_ListMatchItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchItemServiceServer is the server API for MatchItemService service.
// All implementations must embed UnimplementedMatchItemServiceServer
// for forward compatibility.
//
// MatchItemService — per-requirement match analysis
type MatchItemServiceServer interface {
	SetMatchItems(context.Context, *SetMatchItemsReq) (*SetMatchItemsResp, error)
	ListMatchItems(context.Context, *ListMatchItemsReq) (*ListMatchItemsResp, error)
	mustEmbedUnimplementedMatchItemServiceServer()
}

// UnimplementedMatchItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchItemServiceServer struct{}

func (UnimplementedMatchItemServiceServer) SetMatchItems(context.Context, *SetMatchItemsReq) (*SetMatchItemsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMatchItems not implemented")
}
func (UnimplementedMatchItemServiceServer) ListMatchItems(context.Context, *ListMatchItemsReq) (*ListMatchItemsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMatchItems not implemented")
}
func (UnimplementedMatchItemServiceServer) mustEmbedUnimplementedMatchItemServiceServer() {}
func (UnimplementedMatchItemServiceServer) testEmbeddedByValue()                          {}

// UnsafeMatchItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchItemServiceServer will
// result in compilation errors.
type UnsafeMatchItemServiceServer interface {
	mustEmbedUnimplementedMatchItemServiceServer()
}

func RegisterMatchItemServiceServer(s grpc.ServiceRegistrar, srv MatchItemServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchItemService_ServiceDesc, srv)
}

func _MatchItemService_SetMatchItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMatchItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchItemServiceServer).SetMatchItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchItemService_SetMatchItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchItemServiceServer).SetMatchItems(ctx, req.(*SetMatchItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchItemService_ListMatchItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMatchItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchItemServiceServer).ListMatchItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchItemService_ListMatchItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchItemServiceServer).ListMatchItems(ctx, req.(*ListMatchItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchItemService_ServiceDesc is the grpc.ServiceDesc for MatchItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.zhipin.MatchItemService",
	HandlerType: (*MatchItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMatchItems",
			Handler:    _MatchItemService_SetMatchItems_Handler,
		},
		{
			MethodName: "ListMatchItems",
			Handler:    _MatchItemService_ListMatchItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/zhipin/match_item.proto",
}
