// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/zhipin/match_item.proto

package zhipin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNKNOWN MatchStatus = 0
	MatchStatus_MATCH_STATUS_MATCHED MatchStatus = 1
	MatchStatus_MATCH_STATUS_PARTIAL MatchStatus = 2
	MatchStatus_MATCH_STATUS_MISSING MatchStatus = 3
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNKNOWN",
		1: "MATCH_STATUS_MATCHED",
		2: "MATCH_STATUS_PARTIAL",
		3: "MATCH_STATUS_MISSING",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNKNOWN": 0,
		"MATCH_STATUS_MATCHED": 1,
		"MATCH_STATUS_PARTIAL": 2,
		"MATCH_STATUS_MISSING": 3,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_zhipin_match_item_proto_enumTypes[0].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_api_zhipin_match_item_proto_enumTypes[0]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_zhipin_match_item_proto_rawDescGZIP(), []int{0}
}

type MatchItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirement   string                 `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	MatchStatus   int32                  `protobuf:"varint,2,opt,name=match_status,json=matchStatus,proto3" json:"match_status,omitempty"`
	ResumePoint   string                 `protobuf:"bytes,3,opt,name=resume_point,json=resumePoint,proto3" json:"resume_point,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	SortIndex     int32                  `protobuf:"varint,5,opt,name=sort_index,json=sortIndex,proto3" json:"sort_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchItemInput) Reset() {
	*x = MatchItemInput{}
	mi := &file_api_zhipin_match_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchItemInput) ProtoMessage() {}

func (x *MatchItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_zhipin_match_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchItemInput.ProtoReflect.Descriptor instead.
func (*MatchItemInput) Descriptor() ([]byte, []int) {
	return file_api_zhipin_match_item_proto_rawDescGZIP(), []int{0}
}

func (x *MatchItemInput) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *MatchItemInput) GetMatchStatus() int32 {
	if x != nil {
		return x.MatchStatus
	}
	return 0
}

func (x *MatchItemInput) GetResumePoint() string {
	if x != nil {
		return x.ResumePoint
	}
	return ""
}

func (x *MatchItemInput) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *MatchItemInput) GetSortIndex() int32 {
	if x != nil {
		return x.SortIndex
	}
	return 0
}

type SetMatchItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    uint64                 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Items         []*MatchItemInput      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMatchItemsReq) Reset() {
	*x = SetMatchItemsReq{}
	mi := &file_api_zhipin_match_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMatchItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMatchItemsReq) ProtoMessage() {}

func (x *SetMatchItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_zhipin_match_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMatchItemsReq.ProtoReflect.Descriptor instead.
func (*SetMatchItemsReq) Descriptor() ([]byte, []int) {
	return file_api_zhipin_match_item_proto_rawDescGZIP(), []int{1}
}

func (x *SetMatchItemsReq) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *SetMatchItemsReq) GetItems() []*MatchItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetMatchItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMatchItemsResp) Reset() {
	*x = SetMatchItemsResp{}
	mi := &file_api_zhipin_match_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMatchItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMatchItemsResp) ProtoMessage() {}

func (x *SetMatchItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_zhipin_match_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMatchItemsResp.ProtoReflect.Descriptor instead.
func (*SetMatchItemsResp) Descriptor() ([]byte, []int) {
	return file_api_zhipin_match_item_proto_rawDescGZIP(), []int{2}
}

func (x *SetMatchItemsResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListMatchItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    uint64                 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchItemsReq) Reset() {
	*x = ListMatchItemsReq{}
	mi := &file_api_zhipin_match_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchItemsReq) ProtoMessage() {}

func (x *ListMatchItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_zhipin_match_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchItemsReq.ProtoReflect.Descriptor instead.
func (*ListMatchItemsReq) Descriptor() ([]byte, []int) {
	return file_api_zhipin_match_item_proto_rawDescGZIP(), []int{3}
}

func (x *ListMatchItemsReq) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

type MatchItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PositionId    uint64                 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Requirement   string                 `protobuf:"bytes,3,opt,name=requirement,proto3" json:"requirement,omitempty"`
	MatchStatus   int32                  `protobuf:"varint,4,opt,name=match_status,json=matchStatus,proto3" json:"match_status,omitempty"`
	ResumePoint   string                 `protobuf:"bytes,5,opt,name=resume_point,json=resumePoint,proto3" json:"resume_point,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	SortIndex     int32                  `protobuf:"varint,7,opt,name=sort_index,json=sortIndex,proto3" json:"sort_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchItemResp) Reset() {
	*x = MatchItemResp{}
	mi := &file_api_zhipin_match_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchItemResp) ProtoMessage() {}

func (x *MatchItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_zhipin_match_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchItemResp.ProtoReflect.Descriptor instead.
func (*MatchItemResp) Descriptor() ([]byte, []int) {
	return file_api_zhipin_match_item_proto_rawDescGZIP(), []int{4}
}

func (x *MatchItemResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MatchItemResp) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *MatchItemResp) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *MatchItemResp) GetMatchStatus() int32 {
	if x != nil {
		return x.MatchStatus
	}
	return 0
}

func (x *MatchItemResp) GetResumePoint() string {
	if x != nil {
		return x.ResumePoint
	}
	return ""
}

func (x *MatchItemResp) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *MatchItemResp) GetSortIndex() int32 {
	if x != nil {
		return x.SortIndex
	}
	return 0
}

type ListMatchItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MatchItemResp       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMatchItemsResp) Reset() {
	*x = ListMatchItemsResp{}
	mi := &file_api_zhipin_match_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMatchItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchItemsResp) ProtoMessage() {}

func (x *ListMatchItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_zhipin_match_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchItemsResp.ProtoReflect.Descriptor instead.
func (*ListMatchItemsResp) Descriptor() ([]byte, []int) {
	return file_api_zhipin_match_item_proto_rawDescGZIP(), []int{5}
}

func (x *ListMatchItemsResp) GetItems() []*MatchItemResp {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_zhipin_match_item_proto protoreflect.FileDescriptor

const file_api_zhipin_match_item_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/zhipin/match_item.proto\x12\n" +
	"api.zhipin\x1a\x1cgoogle/api/annotations.proto\"\xaf\x01\n" +
	"\x0eMatchItemInput\x12 \n" +
	"\vrequirement\x18\x01 \x01(\tR\vrequirement\x12!\n" +
	"\fmatch_status\x18\x02 \x01(\x05R\vmatchStatus\x12!\n" +
	"\fresume_point\x18\x03 \x01(\tR\vresumePoint\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"sort_index\x18\x05 \x01(\x05R\tsortIndex\"e\n" +
	"\x10SetMatchItemsReq\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x04R\n" +
	"positionId\x120\n" +
	"\x05items\x18\x02 \x03(\v2\x1a.api.zhipin.MatchItemInputR\x05items\")\n" +
	"\x11SetMatchItemsResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"4\n" +
	"\x11ListMatchItemsReq\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x04R\n" +
	"positionId\"\xdf\x01\n" +
	"\rMatchItemResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x04R\n" +
	"positionId\x12 \n" +
	"\vrequirement\x18\x03 \x01(\tR\vrequirement\x12!\n" +
	"\fmatch_status\x18\x04 \x01(\x05R\vmatchStatus\x12!\n" +
	"\fresume_point\x18\x05 \x01(\tR\vresumePoint\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"sort_index\x18\a \x01(\x05R\tsortIndex\"E\n" +
	"\x12ListMatchItemsResp\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.api.zhipin.MatchItemRespR\x05items*u\n" +
	"\vMatchStatus\x12\x18\n" +
	"\x14MATCH_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14MATCH_STATUS_MATCHED\x10\x01\x12\x18\n" +
	"\x14MATCH_STATUS_PARTIAL\x10\x02\x12\x18\n" +
	"\x14MATCH_STATUS_MISSING\x10\x032\x98\x02\n" +
	"\x10MatchItemService\x12\x80\x01\n" +
	"\rSetMatchItems\x12\x1c.api.zhipin.SetMatchItemsReq\x1a\x1d.api.zhipin.SetMatchItemsResp\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/api/position/{position_id}/match-items\x12\x80\x01\n" +
	"\x0eListMatchItems\x12\x1d.api.zhipin.ListMatchItemsReq\x1a\x1e.api.zhipin.ListMatchItemsResp\"/\x82\xd3\xe4\x93\x02)\x12'/api/position/{position_id}/match-itemsBIZGgithub.com/yylego/smart-employee-zhipin/zhipin-kratos/api/zhipin;zhipinb\x06proto3"

var (
	file_api_zhipin_match_item_proto_rawDescOnce sync.Once
	file_api_zhipin_match_item_proto_rawDescData []byte
)

func file_api_zhipin_match_item_proto_rawDescGZIP() []byte {
	file_api_zhipin_match_item_proto_rawDescOnce.Do(func() {
		file_api_zhipin_match_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zhipin_match_item_proto_rawDesc), len(file_api_zhipin_match_item_proto_rawDesc)))
	})
	return file_api_zhipin_match_item_proto_rawDescData
}

var file_api_zhipin_match_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_zhipin_match_item_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_zhipin_match_item_proto_goTypes = []any{
	(MatchStatus)(0),           // 0: api.zhipin.MatchStatus
	(*MatchItemInput)(nil),     // 1: api.zhipin.MatchItemInput
	(*SetMatchItemsReq)(nil),   // 2: api.zhipin.SetMatchItemsReq
	(*SetMatchItemsResp)(nil),  // 3: api.zhipin.SetMatchItemsResp
	(*ListMatchItemsReq)(nil),  // 4: api.zhipin.ListMatchItemsReq
	(*MatchItemResp)(nil),      // 5: api.zhipin.MatchItemResp
	(*ListMatchItemsResp)(nil), // 6: api.zhipin.ListMatchItemsResp
}
var file_api_zhipin_match_item_proto_depIdxs = []int32{
	1, // 0: api.zhipin.SetMatchItemsReq.items:type_name -> api.zhipin.MatchItemInput
	5, // 1: api.zhipin.ListMatchItemsResp.items:type_name -> api.zhipin.MatchItemResp
	2, // 2: api.zhipin.MatchItemService.SetMatchItems:input_type -> api.zhipin.SetMatchItemsReq
	4, // 3: api.zhipin.MatchItemService.ListMatchItems:input_type -> api.zhipin.ListMatchItemsReq
	3, // 4: api.zhipin.MatchItemService.SetMatchItems:output_type -> api.zhipin.SetMatchItemsResp
	6, // 5: api.zhipin.MatchItemService.ListMatchItems:output_type -> api.zhipin.ListMatchItemsResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_zhipin_match_item_proto_init() }
func file_api_zhipin_match_item_proto_init() {
	if File_api_zhipin_match_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zhipin_match_item_proto_rawDesc), len(file_api_zhipin_match_item_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zhipin_match_item_proto_goTypes,
		DependencyIndexes: file_api_zhipin_match_item_proto_depIdxs,
		EnumInfos:         file_api_zhipin_match_item_proto_enumTypes,
		MessageInfos:      file_api_zhipin_match_item_proto_msgTypes,
	}.Build()
	File_api_zhipin_match_item_proto = out.File
	file_api_zhipin_match_item_proto_goTypes = nil
	file_api_zhipin_match_item_proto_depIdxs = nil
}
