// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: zhipin/position.proto

package zhipin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PositionService_CreatePosition_FullMethodName          = "/api.zhipin.PositionService/CreatePosition"
	PositionService_UpdateSalary_FullMethodName            = "/api.zhipin.PositionService/UpdateSalary"
	PositionService_UpdateStatus_FullMethodName            = "/api.zhipin.PositionService/UpdateStatus"
	PositionService_MarkSkipped_FullMethodName             = "/api.zhipin.PositionService/MarkSkipped"
	PositionService_UpdateDuties_FullMethodName            = "/api.zhipin.PositionService/UpdateDuties"
	PositionService_UpdateRequirements_FullMethodName      = "/api.zhipin.PositionService/UpdateRequirements"
	PositionService_UpdateMatchRate_FullMethodName         = "/api.zhipin.PositionService/UpdateMatchRate"
	PositionService_UpdateNotes_FullMethodName             = "/api.zhipin.PositionService/UpdateNotes"
	PositionService_UpdateRecruiter_FullMethodName         = "/api.zhipin.PositionService/UpdateRecruiter"
	PositionService_GetPosition_FullMethodName             = "/api.zhipin.PositionService/GetPosition"
	PositionService_GetPositionByJobId_FullMethodName      = "/api.zhipin.PositionService/GetPositionByJobId"
	PositionService_ListPositions_FullMethodName           = "/api.zhipin.PositionService/ListPositions"
	PositionService_CheckJobId_FullMethodName              = "/api.zhipin.PositionService/CheckJobId"
	PositionService_BatchCheckJobIds_FullMethodName        = "/api.zhipin.PositionService/BatchCheckJobIds"
	PositionService_ListStalePositions_FullMethodName      = "/api.zhipin.PositionService/ListStalePositions"
	PositionService_ListNeedReplyPositions_FullMethodName  = "/api.zhipin.PositionService/ListNeedReplyPositions"
	PositionService_ListNeedResendPositions_FullMethodName = "/api.zhipin.PositionService/ListNeedResendPositions"
	PositionService_UpdateEncBossId_FullMethodName         = "/api.zhipin.PositionService/UpdateEncBossId"
	PositionService_SyncPosition_FullMethodName            = "/api.zhipin.PositionService/SyncPosition"
)

// PositionServiceClient is the client API for PositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PositionService — job position CRUD and status tracking
type PositionServiceClient interface {
	CreatePosition(ctx context.Context, in *CreatePositionReq, opts ...grpc.CallOption) (*PositionResp, error)
	UpdateSalary(ctx context.Context, in *UpdateSalaryReq, opts ...grpc.CallOption) (*PositionResp, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*PositionResp, error)
	MarkSkipped(ctx context.Context, in *MarkSkippedReq, opts ...grpc.CallOption) (*PositionResp, error)
	UpdateDuties(ctx context.Context, in *UpdateDutiesReq, opts ...grpc.CallOption) (*PositionResp, error)
	UpdateRequirements(ctx context.Context, in *UpdateRequirementsReq, opts ...grpc.CallOption) (*PositionResp, error)
	UpdateMatchRate(ctx context.Context, in *UpdateMatchRateReq, opts ...grpc.CallOption) (*PositionResp, error)
	UpdateNotes(ctx context.Context, in *UpdateNotesReq, opts ...grpc.CallOption) (*PositionResp, error)
	UpdateRecruiter(ctx context.Context, in *UpdateRecruiterReq, opts ...grpc.CallOption) (*PositionResp, error)
	GetPosition(ctx context.Context, in *GetPositionReq, opts ...grpc.CallOption) (*PositionDetailResp, error)
	GetPositionByJobId(ctx context.Context, in *GetPositionByJobIdReq, opts ...grpc.CallOption) (*PositionDetailResp, error)
	ListPositions(ctx context.Context, in *ListPositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error)
	CheckJobId(ctx context.Context, in *CheckJobIdReq, opts ...grpc.CallOption) (*CheckJobIdResp, error)
	// Batch check multiple jobIds at once — for dedup after loading full search results
	BatchCheckJobIds(ctx context.Context, in *BatchCheckJobIdsReq, opts ...grpc.CallOption) (*BatchCheckJobIdsResp, error)
	// Find positions not contacted in the last N hours — for follow-up
	ListStalePositions(ctx context.Context, in *ListStalePositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error)
	// Find positions where last message is from recruiter (we need to reply)
	ListNeedReplyPositions(ctx context.Context, in *ListNeedReplyPositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error)
	// Find positions that need resume resend (last resume != given version)
	ListNeedResendPositions(ctx context.Context, in *ListNeedResendPositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error)
	// Update encBossId
	UpdateEncBossId(ctx context.Context, in *UpdateEncBossIdReq, opts ...grpc.CallOption) (*PositionResp, error)
	// Full sync — upsert position + replace matchItems + replace chat messages in one call
	SyncPosition(ctx context.Context, in *SyncPositionReq, opts ...grpc.CallOption) (*SyncPositionResp, error)
}

type positionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionServiceClient(cc grpc.ClientConnInterface) PositionServiceClient {
	return &positionServiceClient{cc}
}

func (c *positionServiceClient) CreatePosition(ctx context.Context, in *CreatePositionReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_CreatePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateSalary(ctx context.Context, in *UpdateSalaryReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateSalary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) MarkSkipped(ctx context.Context, in *MarkSkippedReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_MarkSkipped_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateDuties(ctx context.Context, in *UpdateDutiesReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateDuties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateRequirements(ctx context.Context, in *UpdateRequirementsReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateMatchRate(ctx context.Context, in *UpdateMatchRateReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateMatchRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateNotes(ctx context.Context, in *UpdateNotesReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateRecruiter(ctx context.Context, in *UpdateRecruiterReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateRecruiter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetPosition(ctx context.Context, in *GetPositionReq, opts ...grpc.CallOption) (*PositionDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionDetailResp)
	err := c.cc.Invoke(ctx, PositionService_GetPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetPositionByJobId(ctx context.Context, in *GetPositionByJobIdReq, opts ...grpc.CallOption) (*PositionDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionDetailResp)
	err := c.cc.Invoke(ctx, PositionService_GetPositionByJobId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) ListPositions(ctx context.Context, in *ListPositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionsResp)
	err := c.cc.Invoke(ctx, PositionService_ListPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) CheckJobId(ctx context.Context, in *CheckJobIdReq, opts ...grpc.CallOption) (*CheckJobIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckJobIdResp)
	err := c.cc.Invoke(ctx, PositionService_CheckJobId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) BatchCheckJobIds(ctx context.Context, in *BatchCheckJobIdsReq, opts ...grpc.CallOption) (*BatchCheckJobIdsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckJobIdsResp)
	err := c.cc.Invoke(ctx, PositionService_BatchCheckJobIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) ListStalePositions(ctx context.Context, in *ListStalePositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionsResp)
	err := c.cc.Invoke(ctx, PositionService_ListStalePositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) ListNeedReplyPositions(ctx context.Context, in *ListNeedReplyPositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionsResp)
	err := c.cc.Invoke(ctx, PositionService_ListNeedReplyPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) ListNeedResendPositions(ctx context.Context, in *ListNeedResendPositionsReq, opts ...grpc.CallOption) (*ListPositionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionsResp)
	err := c.cc.Invoke(ctx, PositionService_ListNeedResendPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) UpdateEncBossId(ctx context.Context, in *UpdateEncBossIdReq, opts ...grpc.CallOption) (*PositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResp)
	err := c.cc.Invoke(ctx, PositionService_UpdateEncBossId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) SyncPosition(ctx context.Context, in *SyncPositionReq, opts ...grpc.CallOption) (*SyncPositionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncPositionResp)
	err := c.cc.Invoke(ctx, PositionService_SyncPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PositionServiceServer is the server API for PositionService service.
// All implementations must embed UnimplementedPositionServiceServer
// for forward compatibility.
//
// PositionService — job position CRUD and status tracking
type PositionServiceServer interface {
	CreatePosition(context.Context, *CreatePositionReq) (*PositionResp, error)
	UpdateSalary(context.Context, *UpdateSalaryReq) (*PositionResp, error)
	UpdateStatus(context.Context, *UpdateStatusReq) (*PositionResp, error)
	MarkSkipped(context.Context, *MarkSkippedReq) (*PositionResp, error)
	UpdateDuties(context.Context, *UpdateDutiesReq) (*PositionResp, error)
	UpdateRequirements(context.Context, *UpdateRequirementsReq) (*PositionResp, error)
	UpdateMatchRate(context.Context, *UpdateMatchRateReq) (*PositionResp, error)
	UpdateNotes(context.Context, *UpdateNotesReq) (*PositionResp, error)
	UpdateRecruiter(context.Context, *UpdateRecruiterReq) (*PositionResp, error)
	GetPosition(context.Context, *GetPositionReq) (*PositionDetailResp, error)
	GetPositionByJobId(context.Context, *GetPositionByJobIdReq) (*PositionDetailResp, error)
	ListPositions(context.Context, *ListPositionsReq) (*ListPositionsResp, error)
	CheckJobId(context.Context, *CheckJobIdReq) (*CheckJobIdResp, error)
	// Batch check multiple jobIds at once — for dedup after loading full search results
	BatchCheckJobIds(context.Context, *BatchCheckJobIdsReq) (*BatchCheckJobIdsResp, error)
	// Find positions not contacted in the last N hours — for follow-up
	ListStalePositions(context.Context, *ListStalePositionsReq) (*ListPositionsResp, error)
	// Find positions where last message is from recruiter (we need to reply)
	ListNeedReplyPositions(context.Context, *ListNeedReplyPositionsReq) (*ListPositionsResp, error)
	// Find positions that need resume resend (last resume != given version)
	ListNeedResendPositions(context.Context, *ListNeedResendPositionsReq) (*ListPositionsResp, error)
	// Update encBossId
	UpdateEncBossId(context.Context, *UpdateEncBossIdReq) (*PositionResp, error)
	// Full sync — upsert position + replace matchItems + replace chat messages in one call
	SyncPosition(context.Context, *SyncPositionReq) (*SyncPositionResp, error)
	mustEmbedUnimplementedPositionServiceServer()
}

// UnimplementedPositionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPositionServiceServer struct{}

func (UnimplementedPositionServiceServer) CreatePosition(context.Context, *CreatePositionReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePosition not implemented")
}
func (UnimplementedPositionServiceServer) UpdateSalary(context.Context, *UpdateSalaryReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSalary not implemented")
}
func (UnimplementedPositionServiceServer) UpdateStatus(context.Context, *UpdateStatusReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedPositionServiceServer) MarkSkipped(context.Context, *MarkSkippedReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkSkipped not implemented")
}
func (UnimplementedPositionServiceServer) UpdateDuties(context.Context, *UpdateDutiesReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDuties not implemented")
}
func (UnimplementedPositionServiceServer) UpdateRequirements(context.Context, *UpdateRequirementsReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRequirements not implemented")
}
func (UnimplementedPositionServiceServer) UpdateMatchRate(context.Context, *UpdateMatchRateReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMatchRate not implemented")
}
func (UnimplementedPositionServiceServer) UpdateNotes(context.Context, *UpdateNotesReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNotes not implemented")
}
func (UnimplementedPositionServiceServer) UpdateRecruiter(context.Context, *UpdateRecruiterReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRecruiter not implemented")
}
func (UnimplementedPositionServiceServer) GetPosition(context.Context, *GetPositionReq) (*PositionDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedPositionServiceServer) GetPositionByJobId(context.Context, *GetPositionByJobIdReq) (*PositionDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositionByJobId not implemented")
}
func (UnimplementedPositionServiceServer) ListPositions(context.Context, *ListPositionsReq) (*ListPositionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPositions not implemented")
}
func (UnimplementedPositionServiceServer) CheckJobId(context.Context, *CheckJobIdReq) (*CheckJobIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckJobId not implemented")
}
func (UnimplementedPositionServiceServer) BatchCheckJobIds(context.Context, *BatchCheckJobIdsReq) (*BatchCheckJobIdsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCheckJobIds not implemented")
}
func (UnimplementedPositionServiceServer) ListStalePositions(context.Context, *ListStalePositionsReq) (*ListPositionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStalePositions not implemented")
}
func (UnimplementedPositionServiceServer) ListNeedReplyPositions(context.Context, *ListNeedReplyPositionsReq) (*ListPositionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNeedReplyPositions not implemented")
}
func (UnimplementedPositionServiceServer) ListNeedResendPositions(context.Context, *ListNeedResendPositionsReq) (*ListPositionsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNeedResendPositions not implemented")
}
func (UnimplementedPositionServiceServer) UpdateEncBossId(context.Context, *UpdateEncBossIdReq) (*PositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEncBossId not implemented")
}
func (UnimplementedPositionServiceServer) SyncPosition(context.Context, *SyncPositionReq) (*SyncPositionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncPosition not implemented")
}
func (UnimplementedPositionServiceServer) mustEmbedUnimplementedPositionServiceServer() {}
func (UnimplementedPositionServiceServer) testEmbeddedByValue()                         {}

// UnsafePositionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PositionServiceServer will
// result in compilation errors.
type UnsafePositionServiceServer interface {
	mustEmbedUnimplementedPositionServiceServer()
}

func RegisterPositionServiceServer(s grpc.ServiceRegistrar, srv PositionServiceServer) {
	// If the following call panics, it indicates UnimplementedPositionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PositionService_ServiceDesc, srv)
}

func _PositionService_CreatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).CreatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_CreatePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).CreatePosition(ctx, req.(*CreatePositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSalaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateSalary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateSalary(ctx, req.(*UpdateSalaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateStatus(ctx, req.(*UpdateStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_MarkSkipped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkSkippedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).MarkSkipped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_MarkSkipped_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).MarkSkipped(ctx, req.(*MarkSkippedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateDuties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDutiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateDuties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateDuties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateDuties(ctx, req.(*UpdateDutiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequirementsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateRequirements(ctx, req.(*UpdateRequirementsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateMatchRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMatchRateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateMatchRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateMatchRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateMatchRate(ctx, req.(*UpdateMatchRateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateNotes(ctx, req.(*UpdateNotesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateRecruiter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecruiterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateRecruiter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateRecruiter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateRecruiter(ctx, req.(*UpdateRecruiterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetPosition(ctx, req.(*GetPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetPositionByJobId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionByJobIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetPositionByJobId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetPositionByJobId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetPositionByJobId(ctx, req.(*GetPositionByJobIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPositionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_ListPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).ListPositions(ctx, req.(*ListPositionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_CheckJobId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckJobIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).CheckJobId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_CheckJobId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).CheckJobId(ctx, req.(*CheckJobIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_BatchCheckJobIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckJobIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).BatchCheckJobIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_BatchCheckJobIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).BatchCheckJobIds(ctx, req.(*BatchCheckJobIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_ListStalePositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStalePositionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).ListStalePositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_ListStalePositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).ListStalePositions(ctx, req.(*ListStalePositionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_ListNeedReplyPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNeedReplyPositionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).ListNeedReplyPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_ListNeedReplyPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).ListNeedReplyPositions(ctx, req.(*ListNeedReplyPositionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_ListNeedResendPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNeedResendPositionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).ListNeedResendPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_ListNeedResendPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).ListNeedResendPositions(ctx, req.(*ListNeedResendPositionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_UpdateEncBossId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEncBossIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).UpdateEncBossId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_UpdateEncBossId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).UpdateEncBossId(ctx, req.(*UpdateEncBossIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_SyncPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncPositionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).SyncPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_SyncPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).SyncPosition(ctx, req.(*SyncPositionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PositionService_ServiceDesc is the grpc.ServiceDesc for PositionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PositionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.zhipin.PositionService",
	HandlerType: (*PositionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePosition",
			Handler:    _PositionService_CreatePosition_Handler,
		},
		{
			MethodName: "UpdateSalary",
			Handler:    _PositionService_UpdateSalary_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _PositionService_UpdateStatus_Handler,
		},
		{
			MethodName: "MarkSkipped",
			Handler:    _PositionService_MarkSkipped_Handler,
		},
		{
			MethodName: "UpdateDuties",
			Handler:    _PositionService_UpdateDuties_Handler,
		},
		{
			MethodName: "UpdateRequirements",
			Handler:    _PositionService_UpdateRequirements_Handler,
		},
		{
			MethodName: "UpdateMatchRate",
			Handler:    _PositionService_UpdateMatchRate_Handler,
		},
		{
			MethodName: "UpdateNotes",
			Handler:    _PositionService_UpdateNotes_Handler,
		},
		{
			MethodName: "UpdateRecruiter",
			Handler:    _PositionService_UpdateRecruiter_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _PositionService_GetPosition_Handler,
		},
		{
			MethodName: "GetPositionByJobId",
			Handler:    _PositionService_GetPositionByJobId_Handler,
		},
		{
			MethodName: "ListPositions",
			Handler:    _PositionService_ListPositions_Handler,
		},
		{
			MethodName: "CheckJobId",
			Handler:    _PositionService_CheckJobId_Handler,
		},
		{
			MethodName: "BatchCheckJobIds",
			Handler:    _PositionService_BatchCheckJobIds_Handler,
		},
		{
			MethodName: "ListStalePositions",
			Handler:    _PositionService_ListStalePositions_Handler,
		},
		{
			MethodName: "ListNeedReplyPositions",
			Handler:    _PositionService_ListNeedReplyPositions_Handler,
		},
		{
			MethodName: "ListNeedResendPositions",
			Handler:    _PositionService_ListNeedResendPositions_Handler,
		},
		{
			MethodName: "UpdateEncBossId",
			Handler:    _PositionService_UpdateEncBossId_Handler,
		},
		{
			MethodName: "SyncPosition",
			Handler:    _PositionService_SyncPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhipin/position.proto",
}
