// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: zhipin/position.proto

package zhipin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionStatus int32

const (
	PositionStatus_POSITION_STATUS_UNKNOWN      PositionStatus = 0
	PositionStatus_POSITION_STATUS_PENDING      PositionStatus = 1
	PositionStatus_POSITION_STATUS_SKIPPED      PositionStatus = 2
	PositionStatus_POSITION_STATUS_CHAT_LIMITED PositionStatus = 3
	PositionStatus_POSITION_STATUS_MSG_SENT     PositionStatus = 4
	PositionStatus_POSITION_STATUS_REPLIED      PositionStatus = 5
	PositionStatus_POSITION_STATUS_RESUME_SENT  PositionStatus = 6
	PositionStatus_POSITION_STATUS_INTERVIEWING PositionStatus = 7
	PositionStatus_POSITION_STATUS_OFFERED      PositionStatus = 8
	PositionStatus_POSITION_STATUS_REJECTED     PositionStatus = 9
	PositionStatus_POSITION_STATUS_NO_CONTACT   PositionStatus = 10
)

// Enum value maps for PositionStatus.
var (
	PositionStatus_name = map[int32]string{
		0:  "POSITION_STATUS_UNKNOWN",
		1:  "POSITION_STATUS_PENDING",
		2:  "POSITION_STATUS_SKIPPED",
		3:  "POSITION_STATUS_CHAT_LIMITED",
		4:  "POSITION_STATUS_MSG_SENT",
		5:  "POSITION_STATUS_REPLIED",
		6:  "POSITION_STATUS_RESUME_SENT",
		7:  "POSITION_STATUS_INTERVIEWING",
		8:  "POSITION_STATUS_OFFERED",
		9:  "POSITION_STATUS_REJECTED",
		10: "POSITION_STATUS_NO_CONTACT",
	}
	PositionStatus_value = map[string]int32{
		"POSITION_STATUS_UNKNOWN":      0,
		"POSITION_STATUS_PENDING":      1,
		"POSITION_STATUS_SKIPPED":      2,
		"POSITION_STATUS_CHAT_LIMITED": 3,
		"POSITION_STATUS_MSG_SENT":     4,
		"POSITION_STATUS_REPLIED":      5,
		"POSITION_STATUS_RESUME_SENT":  6,
		"POSITION_STATUS_INTERVIEWING": 7,
		"POSITION_STATUS_OFFERED":      8,
		"POSITION_STATUS_REJECTED":     9,
		"POSITION_STATUS_NO_CONTACT":   10,
	}
)

func (x PositionStatus) Enum() *PositionStatus {
	p := new(PositionStatus)
	*p = x
	return p
}

func (x PositionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zhipin_position_proto_enumTypes[0].Descriptor()
}

func (PositionStatus) Type() protoreflect.EnumType {
	return &file_zhipin_position_proto_enumTypes[0]
}

func (x PositionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionStatus.Descriptor instead.
func (PositionStatus) EnumDescriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{0}
}

type CreatePositionReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	JobId         string                  `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Title         string                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                  `protobuf:"bytes,3,opt,name=company,proto3" json:"company,omitempty"`
	SalaryRange   string                  `protobuf:"bytes,4,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	SalaryMin     int32                   `protobuf:"varint,5,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax     int32                   `protobuf:"varint,6,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	City          string                  `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Link          string                  `protobuf:"bytes,8,opt,name=link,proto3" json:"link,omitempty"`
	Recruiter     string                  `protobuf:"bytes,9,opt,name=recruiter,proto3" json:"recruiter,omitempty"`
	EncBossId     string                  `protobuf:"bytes,10,opt,name=enc_boss_id,json=encBossId,proto3" json:"enc_boss_id,omitempty"`
	IsHunter      bool                    `protobuf:"varint,11,opt,name=is_hunter,json=isHunter,proto3" json:"is_hunter,omitempty"`
	Duties        string                  `protobuf:"bytes,12,opt,name=duties,proto3" json:"duties,omitempty"`
	Requirements  string                  `protobuf:"bytes,13,opt,name=requirements,proto3" json:"requirements,omitempty"`
	Notes         string                  `protobuf:"bytes,14,opt,name=notes,proto3" json:"notes,omitempty"`
	MatchItems    []*RequirementItemInput `protobuf:"bytes,15,rep,name=match_items,json=matchItems,proto3" json:"match_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePositionReq) Reset() {
	*x = CreatePositionReq{}
	mi := &file_zhipin_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePositionReq) ProtoMessage() {}

func (x *CreatePositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePositionReq.ProtoReflect.Descriptor instead.
func (*CreatePositionReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePositionReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CreatePositionReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePositionReq) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreatePositionReq) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *CreatePositionReq) GetSalaryMin() int32 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *CreatePositionReq) GetSalaryMax() int32 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *CreatePositionReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreatePositionReq) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *CreatePositionReq) GetRecruiter() string {
	if x != nil {
		return x.Recruiter
	}
	return ""
}

func (x *CreatePositionReq) GetEncBossId() string {
	if x != nil {
		return x.EncBossId
	}
	return ""
}

func (x *CreatePositionReq) GetIsHunter() bool {
	if x != nil {
		return x.IsHunter
	}
	return false
}

func (x *CreatePositionReq) GetDuties() string {
	if x != nil {
		return x.Duties
	}
	return ""
}

func (x *CreatePositionReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *CreatePositionReq) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreatePositionReq) GetMatchItems() []*RequirementItemInput {
	if x != nil {
		return x.MatchItems
	}
	return nil
}

type UpdateSalaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SalaryRange   string                 `protobuf:"bytes,2,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	SalaryMin     int32                  `protobuf:"varint,3,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax     int32                  `protobuf:"varint,4,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSalaryReq) Reset() {
	*x = UpdateSalaryReq{}
	mi := &file_zhipin_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSalaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSalaryReq) ProtoMessage() {}

func (x *UpdateSalaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSalaryReq.ProtoReflect.Descriptor instead.
func (*UpdateSalaryReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSalaryReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSalaryReq) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *UpdateSalaryReq) GetSalaryMin() int32 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *UpdateSalaryReq) GetSalaryMax() int32 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

type UpdateStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusReq) Reset() {
	*x = UpdateStatusReq{}
	mi := &file_zhipin_position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusReq) ProtoMessage() {}

func (x *UpdateStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateStatusReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStatusReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MarkSkippedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkSkippedReq) Reset() {
	*x = MarkSkippedReq{}
	mi := &file_zhipin_position_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkSkippedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkSkippedReq) ProtoMessage() {}

func (x *MarkSkippedReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkSkippedReq.ProtoReflect.Descriptor instead.
func (*MarkSkippedReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{3}
}

func (x *MarkSkippedReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MarkSkippedReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateDutiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Duties        string                 `protobuf:"bytes,2,opt,name=duties,proto3" json:"duties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDutiesReq) Reset() {
	*x = UpdateDutiesReq{}
	mi := &file_zhipin_position_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDutiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDutiesReq) ProtoMessage() {}

func (x *UpdateDutiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDutiesReq.ProtoReflect.Descriptor instead.
func (*UpdateDutiesReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDutiesReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDutiesReq) GetDuties() string {
	if x != nil {
		return x.Duties
	}
	return ""
}

type UpdateRequirementsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Requirements  string                 `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequirementsReq) Reset() {
	*x = UpdateRequirementsReq{}
	mi := &file_zhipin_position_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequirementsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequirementsReq) ProtoMessage() {}

func (x *UpdateRequirementsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequirementsReq.ProtoReflect.Descriptor instead.
func (*UpdateRequirementsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequirementsReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequirementsReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

type UpdateMatchRateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MatchRate     int32                  `protobuf:"varint,2,opt,name=match_rate,json=matchRate,proto3" json:"match_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMatchRateReq) Reset() {
	*x = UpdateMatchRateReq{}
	mi := &file_zhipin_position_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMatchRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMatchRateReq) ProtoMessage() {}

func (x *UpdateMatchRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMatchRateReq.ProtoReflect.Descriptor instead.
func (*UpdateMatchRateReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMatchRateReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMatchRateReq) GetMatchRate() int32 {
	if x != nil {
		return x.MatchRate
	}
	return 0
}

type UpdateNotesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Notes         string                 `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNotesReq) Reset() {
	*x = UpdateNotesReq{}
	mi := &file_zhipin_position_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNotesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNotesReq) ProtoMessage() {}

func (x *UpdateNotesReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNotesReq.ProtoReflect.Descriptor instead.
func (*UpdateNotesReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNotesReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNotesReq) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateRecruiterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Recruiter     string                 `protobuf:"bytes,2,opt,name=recruiter,proto3" json:"recruiter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecruiterReq) Reset() {
	*x = UpdateRecruiterReq{}
	mi := &file_zhipin_position_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecruiterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecruiterReq) ProtoMessage() {}

func (x *UpdateRecruiterReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecruiterReq.ProtoReflect.Descriptor instead.
func (*UpdateRecruiterReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRecruiterReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRecruiterReq) GetRecruiter() string {
	if x != nil {
		return x.Recruiter
	}
	return ""
}

type GetPositionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionReq) Reset() {
	*x = GetPositionReq{}
	mi := &file_zhipin_position_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionReq) ProtoMessage() {}

func (x *GetPositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionReq.ProtoReflect.Descriptor instead.
func (*GetPositionReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{9}
}

func (x *GetPositionReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPositionByJobIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionByJobIdReq) Reset() {
	*x = GetPositionByJobIdReq{}
	mi := &file_zhipin_position_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionByJobIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionByJobIdReq) ProtoMessage() {}

func (x *GetPositionByJobIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionByJobIdReq.ProtoReflect.Descriptor instead.
func (*GetPositionByJobIdReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{10}
}

func (x *GetPositionByJobIdReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ListPositionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsReq) Reset() {
	*x = ListPositionsReq{}
	mi := &file_zhipin_position_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsReq) ProtoMessage() {}

func (x *ListPositionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsReq.ProtoReflect.Descriptor instead.
func (*ListPositionsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{11}
}

func (x *ListPositionsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListPositionsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPositionsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CheckJobIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckJobIdReq) Reset() {
	*x = CheckJobIdReq{}
	mi := &file_zhipin_position_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckJobIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckJobIdReq) ProtoMessage() {}

func (x *CheckJobIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckJobIdReq.ProtoReflect.Descriptor instead.
func (*CheckJobIdReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{12}
}

func (x *CheckJobIdReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CheckJobIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PositionId    uint64                 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckJobIdResp) Reset() {
	*x = CheckJobIdResp{}
	mi := &file_zhipin_position_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckJobIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckJobIdResp) ProtoMessage() {}

func (x *CheckJobIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckJobIdResp.ProtoReflect.Descriptor instead.
func (*CheckJobIdResp) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{13}
}

func (x *CheckJobIdResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckJobIdResp) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *CheckJobIdResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BatchCheckJobIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobIds        []string               `protobuf:"bytes,1,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"` // list of 28-char jobIds to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckJobIdsReq) Reset() {
	*x = BatchCheckJobIdsReq{}
	mi := &file_zhipin_position_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckJobIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckJobIdsReq) ProtoMessage() {}

func (x *BatchCheckJobIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckJobIdsReq.ProtoReflect.Descriptor instead.
func (*BatchCheckJobIdsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{14}
}

func (x *BatchCheckJobIdsReq) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

type BatchCheckJobIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*JobIdCheckResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckJobIdsResp) Reset() {
	*x = BatchCheckJobIdsResp{}
	mi := &file_zhipin_position_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckJobIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckJobIdsResp) ProtoMessage() {}

func (x *BatchCheckJobIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckJobIdsResp.ProtoReflect.Descriptor instead.
func (*BatchCheckJobIdsResp) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{15}
}

func (x *BatchCheckJobIdsResp) GetResults() []*JobIdCheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type JobIdCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	PositionId    uint64                 `protobuf:"varint,3,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"` // 0 if not exists
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                           // position status if exists
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobIdCheckResult) Reset() {
	*x = JobIdCheckResult{}
	mi := &file_zhipin_position_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobIdCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobIdCheckResult) ProtoMessage() {}

func (x *JobIdCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobIdCheckResult.ProtoReflect.Descriptor instead.
func (*JobIdCheckResult) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{16}
}

func (x *JobIdCheckResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobIdCheckResult) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *JobIdCheckResult) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *JobIdCheckResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListStalePositionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaleHours    int32                  `protobuf:"varint,1,opt,name=stale_hours,json=staleHours,proto3" json:"stale_hours,omitempty"` // positions not contacted in the last N hours
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStalePositionsReq) Reset() {
	*x = ListStalePositionsReq{}
	mi := &file_zhipin_position_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStalePositionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStalePositionsReq) ProtoMessage() {}

func (x *ListStalePositionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStalePositionsReq.ProtoReflect.Descriptor instead.
func (*ListStalePositionsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{17}
}

func (x *ListStalePositionsReq) GetStaleHours() int32 {
	if x != nil {
		return x.StaleHours
	}
	return 0
}

type ListNeedReplyPositionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNeedReplyPositionsReq) Reset() {
	*x = ListNeedReplyPositionsReq{}
	mi := &file_zhipin_position_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNeedReplyPositionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNeedReplyPositionsReq) ProtoMessage() {}

func (x *ListNeedReplyPositionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNeedReplyPositionsReq.ProtoReflect.Descriptor instead.
func (*ListNeedReplyPositionsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{18}
}

type ListNeedResendPositionsReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	LatestResumeVersion string                 `protobuf:"bytes,1,opt,name=latest_resume_version,json=latestResumeVersion,proto3" json:"latest_resume_version,omitempty"` // e.g. "简历-杨亦乐-v20260320.pdf"
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListNeedResendPositionsReq) Reset() {
	*x = ListNeedResendPositionsReq{}
	mi := &file_zhipin_position_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNeedResendPositionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNeedResendPositionsReq) ProtoMessage() {}

func (x *ListNeedResendPositionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNeedResendPositionsReq.ProtoReflect.Descriptor instead.
func (*ListNeedResendPositionsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{19}
}

func (x *ListNeedResendPositionsReq) GetLatestResumeVersion() string {
	if x != nil {
		return x.LatestResumeVersion
	}
	return ""
}

type UpdateEncBossIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EncBossId     string                 `protobuf:"bytes,2,opt,name=enc_boss_id,json=encBossId,proto3" json:"enc_boss_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEncBossIdReq) Reset() {
	*x = UpdateEncBossIdReq{}
	mi := &file_zhipin_position_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEncBossIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEncBossIdReq) ProtoMessage() {}

func (x *UpdateEncBossIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEncBossIdReq.ProtoReflect.Descriptor instead.
func (*UpdateEncBossIdReq) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateEncBossIdReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEncBossIdReq) GetEncBossId() string {
	if x != nil {
		return x.EncBossId
	}
	return ""
}

type PositionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	SalaryRange   string                 `protobuf:"bytes,5,opt,name=salary_range,json=salaryRange,proto3" json:"salary_range,omitempty"`
	SalaryMin     int32                  `protobuf:"varint,6,opt,name=salary_min,json=salaryMin,proto3" json:"salary_min,omitempty"`
	SalaryMax     int32                  `protobuf:"varint,7,opt,name=salary_max,json=salaryMax,proto3" json:"salary_max,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Link          string                 `protobuf:"bytes,9,opt,name=link,proto3" json:"link,omitempty"`
	Recruiter     string                 `protobuf:"bytes,10,opt,name=recruiter,proto3" json:"recruiter,omitempty"`
	EncBossId     string                 `protobuf:"bytes,11,opt,name=enc_boss_id,json=encBossId,proto3" json:"enc_boss_id,omitempty"`
	IsHunter      bool                   `protobuf:"varint,12,opt,name=is_hunter,json=isHunter,proto3" json:"is_hunter,omitempty"`
	Status        int32                  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	SkipReason    string                 `protobuf:"bytes,14,opt,name=skip_reason,json=skipReason,proto3" json:"skip_reason,omitempty"`
	MatchRate     int32                  `protobuf:"varint,15,opt,name=match_rate,json=matchRate,proto3" json:"match_rate,omitempty"`
	Notes         string                 `protobuf:"bytes,16,opt,name=notes,proto3" json:"notes,omitempty"`
	LastCommAt    int64                  `protobuf:"varint,17,opt,name=last_comm_at,json=lastCommAt,proto3" json:"last_comm_at,omitempty"`
	LastCommDir   int32                  `protobuf:"varint,18,opt,name=last_comm_dir,json=lastCommDir,proto3" json:"last_comm_dir,omitempty"`
	LastResume    string                 `protobuf:"bytes,19,opt,name=last_resume,json=lastResume,proto3" json:"last_resume,omitempty"`
	Duties        string                 `protobuf:"bytes,20,opt,name=duties,proto3" json:"duties,omitempty"`
	Requirements  string                 `protobuf:"bytes,21,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionResp) Reset() {
	*x = PositionResp{}
	mi := &file_zhipin_position_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionResp) ProtoMessage() {}

func (x *PositionResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionResp.ProtoReflect.Descriptor instead.
func (*PositionResp) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{21}
}

func (x *PositionResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PositionResp) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PositionResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PositionResp) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *PositionResp) GetSalaryRange() string {
	if x != nil {
		return x.SalaryRange
	}
	return ""
}

func (x *PositionResp) GetSalaryMin() int32 {
	if x != nil {
		return x.SalaryMin
	}
	return 0
}

func (x *PositionResp) GetSalaryMax() int32 {
	if x != nil {
		return x.SalaryMax
	}
	return 0
}

func (x *PositionResp) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PositionResp) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *PositionResp) GetRecruiter() string {
	if x != nil {
		return x.Recruiter
	}
	return ""
}

func (x *PositionResp) GetEncBossId() string {
	if x != nil {
		return x.EncBossId
	}
	return ""
}

func (x *PositionResp) GetIsHunter() bool {
	if x != nil {
		return x.IsHunter
	}
	return false
}

func (x *PositionResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PositionResp) GetSkipReason() string {
	if x != nil {
		return x.SkipReason
	}
	return ""
}

func (x *PositionResp) GetMatchRate() int32 {
	if x != nil {
		return x.MatchRate
	}
	return 0
}

func (x *PositionResp) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *PositionResp) GetLastCommAt() int64 {
	if x != nil {
		return x.LastCommAt
	}
	return 0
}

func (x *PositionResp) GetLastCommDir() int32 {
	if x != nil {
		return x.LastCommDir
	}
	return 0
}

func (x *PositionResp) GetLastResume() string {
	if x != nil {
		return x.LastResume
	}
	return ""
}

func (x *PositionResp) GetDuties() string {
	if x != nil {
		return x.Duties
	}
	return ""
}

func (x *PositionResp) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

type PositionDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionResp          `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	MatchItems    []*RequirementItemResp `protobuf:"bytes,2,rep,name=match_items,json=matchItems,proto3" json:"match_items,omitempty"`
	ChatMessages  []*ChatMessage         `protobuf:"bytes,3,rep,name=chat_messages,json=chatMessages,proto3" json:"chat_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionDetailResp) Reset() {
	*x = PositionDetailResp{}
	mi := &file_zhipin_position_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionDetailResp) ProtoMessage() {}

func (x *PositionDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionDetailResp.ProtoReflect.Descriptor instead.
func (*PositionDetailResp) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{22}
}

func (x *PositionDetailResp) GetPosition() *PositionResp {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PositionDetailResp) GetMatchItems() []*RequirementItemResp {
	if x != nil {
		return x.MatchItems
	}
	return nil
}

func (x *PositionDetailResp) GetChatMessages() []*ChatMessage {
	if x != nil {
		return x.ChatMessages
	}
	return nil
}

type ListPositionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PositionResp        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPositionsResp) Reset() {
	*x = ListPositionsResp{}
	mi := &file_zhipin_position_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPositionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPositionsResp) ProtoMessage() {}

func (x *ListPositionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_position_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPositionsResp.ProtoReflect.Descriptor instead.
func (*ListPositionsResp) Descriptor() ([]byte, []int) {
	return file_zhipin_position_proto_rawDescGZIP(), []int{23}
}

func (x *ListPositionsResp) GetItems() []*PositionResp {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListPositionsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_zhipin_position_proto protoreflect.FileDescriptor

const file_zhipin_position_proto_rawDesc = "" +
	"\n" +
	"\x15zhipin/position.proto\x12\n" +
	"api.zhipin\x1a\x1cgoogle/api/annotations.proto\x1a\x1dzhipin/requirement_item.proto\x1a\x1azhipin/communication.proto\"\xd3\x03\n" +
	"\x11CreatePositionReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x03 \x01(\tR\acompany\x12!\n" +
	"\fsalary_range\x18\x04 \x01(\tR\vsalaryRange\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x05 \x01(\x05R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\x06 \x01(\x05R\tsalaryMax\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x12\n" +
	"\x04link\x18\b \x01(\tR\x04link\x12\x1c\n" +
	"\trecruiter\x18\t \x01(\tR\trecruiter\x12\x1e\n" +
	"\venc_boss_id\x18\n" +
	" \x01(\tR\tencBossId\x12\x1b\n" +
	"\tis_hunter\x18\v \x01(\bR\bisHunter\x12\x16\n" +
	"\x06duties\x18\f \x01(\tR\x06duties\x12\"\n" +
	"\frequirements\x18\r \x01(\tR\frequirements\x12\x14\n" +
	"\x05notes\x18\x0e \x01(\tR\x05notes\x12A\n" +
	"\vmatch_items\x18\x0f \x03(\v2 .api.zhipin.RequirementItemInputR\n" +
	"matchItems\"\x82\x01\n" +
	"\x0fUpdateSalaryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fsalary_range\x18\x02 \x01(\tR\vsalaryRange\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x03 \x01(\x05R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\x04 \x01(\x05R\tsalaryMax\"9\n" +
	"\x0fUpdateStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"8\n" +
	"\x0eMarkSkippedReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"9\n" +
	"\x0fUpdateDutiesReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06duties\x18\x02 \x01(\tR\x06duties\"K\n" +
	"\x15UpdateRequirementsReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\"\n" +
	"\frequirements\x18\x02 \x01(\tR\frequirements\"C\n" +
	"\x12UpdateMatchRateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"match_rate\x18\x02 \x01(\x05R\tmatchRate\"6\n" +
	"\x0eUpdateNotesReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\"B\n" +
	"\x12UpdateRecruiterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\trecruiter\x18\x02 \x01(\tR\trecruiter\" \n" +
	"\x0eGetPositionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\".\n" +
	"\x15GetPositionByJobIdReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"[\n" +
	"\x10ListPositionsReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"&\n" +
	"\rCheckJobIdReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"a\n" +
	"\x0eCheckJobIdResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x04R\n" +
	"positionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\".\n" +
	"\x13BatchCheckJobIdsReq\x12\x17\n" +
	"\ajob_ids\x18\x01 \x03(\tR\x06jobIds\"N\n" +
	"\x14BatchCheckJobIdsResp\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.api.zhipin.JobIdCheckResultR\aresults\"z\n" +
	"\x10JobIdCheckResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x1f\n" +
	"\vposition_id\x18\x03 \x01(\x04R\n" +
	"positionId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"8\n" +
	"\x15ListStalePositionsReq\x12\x1f\n" +
	"\vstale_hours\x18\x01 \x01(\x05R\n" +
	"staleHours\"\x1b\n" +
	"\x19ListNeedReplyPositionsReq\"P\n" +
	"\x1aListNeedResendPositionsReq\x122\n" +
	"\x15latest_resume_version\x18\x01 \x01(\tR\x13latestResumeVersion\"D\n" +
	"\x12UpdateEncBossIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1e\n" +
	"\venc_boss_id\x18\x02 \x01(\tR\tencBossId\"\xda\x04\n" +
	"\fPositionResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12!\n" +
	"\fsalary_range\x18\x05 \x01(\tR\vsalaryRange\x12\x1d\n" +
	"\n" +
	"salary_min\x18\x06 \x01(\x05R\tsalaryMin\x12\x1d\n" +
	"\n" +
	"salary_max\x18\a \x01(\x05R\tsalaryMax\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x12\n" +
	"\x04link\x18\t \x01(\tR\x04link\x12\x1c\n" +
	"\trecruiter\x18\n" +
	" \x01(\tR\trecruiter\x12\x1e\n" +
	"\venc_boss_id\x18\v \x01(\tR\tencBossId\x12\x1b\n" +
	"\tis_hunter\x18\f \x01(\bR\bisHunter\x12\x16\n" +
	"\x06status\x18\r \x01(\x05R\x06status\x12\x1f\n" +
	"\vskip_reason\x18\x0e \x01(\tR\n" +
	"skipReason\x12\x1d\n" +
	"\n" +
	"match_rate\x18\x0f \x01(\x05R\tmatchRate\x12\x14\n" +
	"\x05notes\x18\x10 \x01(\tR\x05notes\x12 \n" +
	"\flast_comm_at\x18\x11 \x01(\x03R\n" +
	"lastCommAt\x12\"\n" +
	"\rlast_comm_dir\x18\x12 \x01(\x05R\vlastCommDir\x12\x1f\n" +
	"\vlast_resume\x18\x13 \x01(\tR\n" +
	"lastResume\x12\x16\n" +
	"\x06duties\x18\x14 \x01(\tR\x06duties\x12\"\n" +
	"\frequirements\x18\x15 \x01(\tR\frequirements\"\xca\x01\n" +
	"\x12PositionDetailResp\x124\n" +
	"\bposition\x18\x01 \x01(\v2\x18.api.zhipin.PositionRespR\bposition\x12@\n" +
	"\vmatch_items\x18\x02 \x03(\v2\x1f.api.zhipin.RequirementItemRespR\n" +
	"matchItems\x12<\n" +
	"\rchat_messages\x18\x03 \x03(\v2\x17.api.zhipin.ChatMessageR\fchatMessages\"Y\n" +
	"\x11ListPositionsResp\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.api.zhipin.PositionRespR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*\xe2\x02\n" +
	"\x0ePositionStatus\x12\x1b\n" +
	"\x17POSITION_STATUS_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17POSITION_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17POSITION_STATUS_SKIPPED\x10\x02\x12 \n" +
	"\x1cPOSITION_STATUS_CHAT_LIMITED\x10\x03\x12\x1c\n" +
	"\x18POSITION_STATUS_MSG_SENT\x10\x04\x12\x1b\n" +
	"\x17POSITION_STATUS_REPLIED\x10\x05\x12\x1f\n" +
	"\x1bPOSITION_STATUS_RESUME_SENT\x10\x06\x12 \n" +
	"\x1cPOSITION_STATUS_INTERVIEWING\x10\a\x12\x1b\n" +
	"\x17POSITION_STATUS_OFFERED\x10\b\x12\x1c\n" +
	"\x18POSITION_STATUS_REJECTED\x10\t\x12\x1e\n" +
	"\x1aPOSITION_STATUS_NO_CONTACT\x10\n" +
	"2\xa8\x10\n" +
	"\x0fPositionService\x12c\n" +
	"\x0eCreatePosition\x12\x1d.api.zhipin.CreatePositionReq\x1a\x18.api.zhipin.PositionResp\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/position\x12k\n" +
	"\fUpdateSalary\x12\x1b.api.zhipin.UpdateSalaryReq\x1a\x18.api.zhipin.PositionResp\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/position/{id}/salary\x12k\n" +
	"\fUpdateStatus\x12\x1b.api.zhipin.UpdateStatusReq\x1a\x18.api.zhipin.PositionResp\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/position/{id}/status\x12g\n" +
	"\vMarkSkipped\x12\x1a.api.zhipin.MarkSkippedReq\x1a\x18.api.zhipin.PositionResp\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/position/{id}/skip\x12k\n" +
	"\fUpdateDuties\x12\x1b.api.zhipin.UpdateDutiesReq\x1a\x18.api.zhipin.PositionResp\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/position/{id}/duties\x12}\n" +
	"\x12UpdateRequirements\x12!.api.zhipin.UpdateRequirementsReq\x1a\x18.api.zhipin.PositionResp\"*\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/api/position/{id}/requirements\x12u\n" +
	"\x0fUpdateMatchRate\x12\x1e.api.zhipin.UpdateMatchRateReq\x1a\x18.api.zhipin.PositionResp\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/api/position/{id}/match-rate\x12h\n" +
	"\vUpdateNotes\x12\x1a.api.zhipin.UpdateNotesReq\x1a\x18.api.zhipin.PositionResp\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/position/{id}/notes\x12t\n" +
	"\x0fUpdateRecruiter\x12\x1e.api.zhipin.UpdateRecruiterReq\x1a\x18.api.zhipin.PositionResp\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/api/position/{id}/recruiter\x12e\n" +
	"\vGetPosition\x12\x1a.api.zhipin.GetPositionReq\x1a\x1e.api.zhipin.PositionDetailResp\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/position/{id}\x12{\n" +
	"\x12GetPositionByJobId\x12!.api.zhipin.GetPositionByJobIdReq\x1a\x1e.api.zhipin.PositionDetailResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/position/job/{job_id}\x12d\n" +
	"\rListPositions\x12\x1c.api.zhipin.ListPositionsReq\x1a\x1d.api.zhipin.ListPositionsResp\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/positions\x12i\n" +
	"\n" +
	"CheckJobId\x12\x19.api.zhipin.CheckJobIdReq\x1a\x1a.api.zhipin.CheckJobIdResp\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/position/check/{job_id}\x12|\n" +
	"\x10BatchCheckJobIds\x12\x1f.api.zhipin.BatchCheckJobIdsReq\x1a .api.zhipin.BatchCheckJobIdsResp\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/positions/batch-check\x12t\n" +
	"\x12ListStalePositions\x12!.api.zhipin.ListStalePositionsReq\x1a\x1d.api.zhipin.ListPositionsResp\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/positions/stale\x12\x81\x01\n" +
	"\x16ListNeedReplyPositions\x12%.api.zhipin.ListNeedReplyPositionsReq\x1a\x1d.api.zhipin.ListPositionsResp\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/positions/need-reply\x12\x84\x01\n" +
	"\x17ListNeedResendPositions\x12&.api.zhipin.ListNeedResendPositionsReq\x1a\x1d.api.zhipin.ListPositionsResp\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/positions/need-resend\x12v\n" +
	"\x0fUpdateEncBossId\x12\x1e.api.zhipin.UpdateEncBossIdReq\x1a\x18.api.zhipin.PositionResp\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/api/position/{id}/enc-boss-idBIZGgithub.com/yylego/smart-employee-zhipin/zhipin-kratos/api/zhipin;zhipinb\x06proto3"

var (
	file_zhipin_position_proto_rawDescOnce sync.Once
	file_zhipin_position_proto_rawDescData []byte
)

func file_zhipin_position_proto_rawDescGZIP() []byte {
	file_zhipin_position_proto_rawDescOnce.Do(func() {
		file_zhipin_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhipin_position_proto_rawDesc), len(file_zhipin_position_proto_rawDesc)))
	})
	return file_zhipin_position_proto_rawDescData
}

var file_zhipin_position_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zhipin_position_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_zhipin_position_proto_goTypes = []any{
	(PositionStatus)(0),                // 0: api.zhipin.PositionStatus
	(*CreatePositionReq)(nil),          // 1: api.zhipin.CreatePositionReq
	(*UpdateSalaryReq)(nil),            // 2: api.zhipin.UpdateSalaryReq
	(*UpdateStatusReq)(nil),            // 3: api.zhipin.UpdateStatusReq
	(*MarkSkippedReq)(nil),             // 4: api.zhipin.MarkSkippedReq
	(*UpdateDutiesReq)(nil),            // 5: api.zhipin.UpdateDutiesReq
	(*UpdateRequirementsReq)(nil),      // 6: api.zhipin.UpdateRequirementsReq
	(*UpdateMatchRateReq)(nil),         // 7: api.zhipin.UpdateMatchRateReq
	(*UpdateNotesReq)(nil),             // 8: api.zhipin.UpdateNotesReq
	(*UpdateRecruiterReq)(nil),         // 9: api.zhipin.UpdateRecruiterReq
	(*GetPositionReq)(nil),             // 10: api.zhipin.GetPositionReq
	(*GetPositionByJobIdReq)(nil),      // 11: api.zhipin.GetPositionByJobIdReq
	(*ListPositionsReq)(nil),           // 12: api.zhipin.ListPositionsReq
	(*CheckJobIdReq)(nil),              // 13: api.zhipin.CheckJobIdReq
	(*CheckJobIdResp)(nil),             // 14: api.zhipin.CheckJobIdResp
	(*BatchCheckJobIdsReq)(nil),        // 15: api.zhipin.BatchCheckJobIdsReq
	(*BatchCheckJobIdsResp)(nil),       // 16: api.zhipin.BatchCheckJobIdsResp
	(*JobIdCheckResult)(nil),           // 17: api.zhipin.JobIdCheckResult
	(*ListStalePositionsReq)(nil),      // 18: api.zhipin.ListStalePositionsReq
	(*ListNeedReplyPositionsReq)(nil),  // 19: api.zhipin.ListNeedReplyPositionsReq
	(*ListNeedResendPositionsReq)(nil), // 20: api.zhipin.ListNeedResendPositionsReq
	(*UpdateEncBossIdReq)(nil),         // 21: api.zhipin.UpdateEncBossIdReq
	(*PositionResp)(nil),               // 22: api.zhipin.PositionResp
	(*PositionDetailResp)(nil),         // 23: api.zhipin.PositionDetailResp
	(*ListPositionsResp)(nil),          // 24: api.zhipin.ListPositionsResp
	(*RequirementItemInput)(nil),       // 25: api.zhipin.RequirementItemInput
	(*RequirementItemResp)(nil),        // 26: api.zhipin.RequirementItemResp
	(*ChatMessage)(nil),                // 27: api.zhipin.ChatMessage
}
var file_zhipin_position_proto_depIdxs = []int32{
	25, // 0: api.zhipin.CreatePositionReq.match_items:type_name -> api.zhipin.RequirementItemInput
	17, // 1: api.zhipin.BatchCheckJobIdsResp.results:type_name -> api.zhipin.JobIdCheckResult
	22, // 2: api.zhipin.PositionDetailResp.position:type_name -> api.zhipin.PositionResp
	26, // 3: api.zhipin.PositionDetailResp.match_items:type_name -> api.zhipin.RequirementItemResp
	27, // 4: api.zhipin.PositionDetailResp.chat_messages:type_name -> api.zhipin.ChatMessage
	22, // 5: api.zhipin.ListPositionsResp.items:type_name -> api.zhipin.PositionResp
	1,  // 6: api.zhipin.PositionService.CreatePosition:input_type -> api.zhipin.CreatePositionReq
	2,  // 7: api.zhipin.PositionService.UpdateSalary:input_type -> api.zhipin.UpdateSalaryReq
	3,  // 8: api.zhipin.PositionService.UpdateStatus:input_type -> api.zhipin.UpdateStatusReq
	4,  // 9: api.zhipin.PositionService.MarkSkipped:input_type -> api.zhipin.MarkSkippedReq
	5,  // 10: api.zhipin.PositionService.UpdateDuties:input_type -> api.zhipin.UpdateDutiesReq
	6,  // 11: api.zhipin.PositionService.UpdateRequirements:input_type -> api.zhipin.UpdateRequirementsReq
	7,  // 12: api.zhipin.PositionService.UpdateMatchRate:input_type -> api.zhipin.UpdateMatchRateReq
	8,  // 13: api.zhipin.PositionService.UpdateNotes:input_type -> api.zhipin.UpdateNotesReq
	9,  // 14: api.zhipin.PositionService.UpdateRecruiter:input_type -> api.zhipin.UpdateRecruiterReq
	10, // 15: api.zhipin.PositionService.GetPosition:input_type -> api.zhipin.GetPositionReq
	11, // 16: api.zhipin.PositionService.GetPositionByJobId:input_type -> api.zhipin.GetPositionByJobIdReq
	12, // 17: api.zhipin.PositionService.ListPositions:input_type -> api.zhipin.ListPositionsReq
	13, // 18: api.zhipin.PositionService.CheckJobId:input_type -> api.zhipin.CheckJobIdReq
	15, // 19: api.zhipin.PositionService.BatchCheckJobIds:input_type -> api.zhipin.BatchCheckJobIdsReq
	18, // 20: api.zhipin.PositionService.ListStalePositions:input_type -> api.zhipin.ListStalePositionsReq
	19, // 21: api.zhipin.PositionService.ListNeedReplyPositions:input_type -> api.zhipin.ListNeedReplyPositionsReq
	20, // 22: api.zhipin.PositionService.ListNeedResendPositions:input_type -> api.zhipin.ListNeedResendPositionsReq
	21, // 23: api.zhipin.PositionService.UpdateEncBossId:input_type -> api.zhipin.UpdateEncBossIdReq
	22, // 24: api.zhipin.PositionService.CreatePosition:output_type -> api.zhipin.PositionResp
	22, // 25: api.zhipin.PositionService.UpdateSalary:output_type -> api.zhipin.PositionResp
	22, // 26: api.zhipin.PositionService.UpdateStatus:output_type -> api.zhipin.PositionResp
	22, // 27: api.zhipin.PositionService.MarkSkipped:output_type -> api.zhipin.PositionResp
	22, // 28: api.zhipin.PositionService.UpdateDuties:output_type -> api.zhipin.PositionResp
	22, // 29: api.zhipin.PositionService.UpdateRequirements:output_type -> api.zhipin.PositionResp
	22, // 30: api.zhipin.PositionService.UpdateMatchRate:output_type -> api.zhipin.PositionResp
	22, // 31: api.zhipin.PositionService.UpdateNotes:output_type -> api.zhipin.PositionResp
	22, // 32: api.zhipin.PositionService.UpdateRecruiter:output_type -> api.zhipin.PositionResp
	23, // 33: api.zhipin.PositionService.GetPosition:output_type -> api.zhipin.PositionDetailResp
	23, // 34: api.zhipin.PositionService.GetPositionByJobId:output_type -> api.zhipin.PositionDetailResp
	24, // 35: api.zhipin.PositionService.ListPositions:output_type -> api.zhipin.ListPositionsResp
	14, // 36: api.zhipin.PositionService.CheckJobId:output_type -> api.zhipin.CheckJobIdResp
	16, // 37: api.zhipin.PositionService.BatchCheckJobIds:output_type -> api.zhipin.BatchCheckJobIdsResp
	24, // 38: api.zhipin.PositionService.ListStalePositions:output_type -> api.zhipin.ListPositionsResp
	24, // 39: api.zhipin.PositionService.ListNeedReplyPositions:output_type -> api.zhipin.ListPositionsResp
	24, // 40: api.zhipin.PositionService.ListNeedResendPositions:output_type -> api.zhipin.ListPositionsResp
	22, // 41: api.zhipin.PositionService.UpdateEncBossId:output_type -> api.zhipin.PositionResp
	24, // [24:42] is the sub-list for method output_type
	6,  // [6:24] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_zhipin_position_proto_init() }
func file_zhipin_position_proto_init() {
	if File_zhipin_position_proto != nil {
		return
	}
	file_zhipin_requirement_item_proto_init()
	file_zhipin_communication_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhipin_position_proto_rawDesc), len(file_zhipin_position_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhipin_position_proto_goTypes,
		DependencyIndexes: file_zhipin_position_proto_depIdxs,
		EnumInfos:         file_zhipin_position_proto_enumTypes,
		MessageInfos:      file_zhipin_position_proto_msgTypes,
	}.Build()
	File_zhipin_position_proto = out.File
	file_zhipin_position_proto_goTypes = nil
	file_zhipin_position_proto_depIdxs = nil
}
