// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.0
// source: zhipin/position.proto

package zhipin

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPositionServiceBatchCheckJobIds = "/api.zhipin.PositionService/BatchCheckJobIds"
const OperationPositionServiceCheckJobId = "/api.zhipin.PositionService/CheckJobId"
const OperationPositionServiceCreatePosition = "/api.zhipin.PositionService/CreatePosition"
const OperationPositionServiceGetPosition = "/api.zhipin.PositionService/GetPosition"
const OperationPositionServiceGetPositionByJobId = "/api.zhipin.PositionService/GetPositionByJobId"
const OperationPositionServiceListNeedReplyPositions = "/api.zhipin.PositionService/ListNeedReplyPositions"
const OperationPositionServiceListNeedResendPositions = "/api.zhipin.PositionService/ListNeedResendPositions"
const OperationPositionServiceListPositions = "/api.zhipin.PositionService/ListPositions"
const OperationPositionServiceListStalePositions = "/api.zhipin.PositionService/ListStalePositions"
const OperationPositionServiceMarkSkipped = "/api.zhipin.PositionService/MarkSkipped"
const OperationPositionServiceSyncPosition = "/api.zhipin.PositionService/SyncPosition"
const OperationPositionServiceUpdateDuties = "/api.zhipin.PositionService/UpdateDuties"
const OperationPositionServiceUpdateEncBossId = "/api.zhipin.PositionService/UpdateEncBossId"
const OperationPositionServiceUpdateMatchRate = "/api.zhipin.PositionService/UpdateMatchRate"
const OperationPositionServiceUpdateNotes = "/api.zhipin.PositionService/UpdateNotes"
const OperationPositionServiceUpdateRecruiter = "/api.zhipin.PositionService/UpdateRecruiter"
const OperationPositionServiceUpdateRequirements = "/api.zhipin.PositionService/UpdateRequirements"
const OperationPositionServiceUpdateSalary = "/api.zhipin.PositionService/UpdateSalary"
const OperationPositionServiceUpdateStatus = "/api.zhipin.PositionService/UpdateStatus"

type PositionServiceHTTPServer interface {
	// BatchCheckJobIds Batch check multiple jobIds at once — for dedup after loading full search results
	BatchCheckJobIds(context.Context, *BatchCheckJobIdsReq) (*BatchCheckJobIdsResp, error)
	CheckJobId(context.Context, *CheckJobIdReq) (*CheckJobIdResp, error)
	CreatePosition(context.Context, *CreatePositionReq) (*PositionResp, error)
	GetPosition(context.Context, *GetPositionReq) (*PositionDetailResp, error)
	GetPositionByJobId(context.Context, *GetPositionByJobIdReq) (*PositionDetailResp, error)
	// ListNeedReplyPositions Find positions where last message is from recruiter (we need to reply)
	ListNeedReplyPositions(context.Context, *ListNeedReplyPositionsReq) (*ListPositionsResp, error)
	// ListNeedResendPositions Find positions that need resume resend (last resume != given version)
	ListNeedResendPositions(context.Context, *ListNeedResendPositionsReq) (*ListPositionsResp, error)
	ListPositions(context.Context, *ListPositionsReq) (*ListPositionsResp, error)
	// ListStalePositions Find positions not contacted in the last N hours — for follow-up
	ListStalePositions(context.Context, *ListStalePositionsReq) (*ListPositionsResp, error)
	MarkSkipped(context.Context, *MarkSkippedReq) (*PositionResp, error)
	// SyncPosition Full sync — upsert position + replace matchItems + replace chat messages in one call
	SyncPosition(context.Context, *SyncPositionReq) (*SyncPositionResp, error)
	UpdateDuties(context.Context, *UpdateDutiesReq) (*PositionResp, error)
	// UpdateEncBossId Update encBossId
	UpdateEncBossId(context.Context, *UpdateEncBossIdReq) (*PositionResp, error)
	UpdateMatchRate(context.Context, *UpdateMatchRateReq) (*PositionResp, error)
	UpdateNotes(context.Context, *UpdateNotesReq) (*PositionResp, error)
	UpdateRecruiter(context.Context, *UpdateRecruiterReq) (*PositionResp, error)
	UpdateRequirements(context.Context, *UpdateRequirementsReq) (*PositionResp, error)
	UpdateSalary(context.Context, *UpdateSalaryReq) (*PositionResp, error)
	UpdateStatus(context.Context, *UpdateStatusReq) (*PositionResp, error)
}

func RegisterPositionServiceHTTPServer(s *http.Server, srv PositionServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/position", _PositionService_CreatePosition0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/salary", _PositionService_UpdateSalary0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/status", _PositionService_UpdateStatus0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/skip", _PositionService_MarkSkipped0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/duties", _PositionService_UpdateDuties0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/requirements", _PositionService_UpdateRequirements0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/match-rate", _PositionService_UpdateMatchRate0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/notes", _PositionService_UpdateNotes0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/recruiter", _PositionService_UpdateRecruiter0_HTTP_Handler(srv))
	r.GET("/api/position/{id}", _PositionService_GetPosition0_HTTP_Handler(srv))
	r.GET("/api/position/job/{job_id}", _PositionService_GetPositionByJobId0_HTTP_Handler(srv))
	r.GET("/api/positions", _PositionService_ListPositions0_HTTP_Handler(srv))
	r.GET("/api/position/check/{job_id}", _PositionService_CheckJobId0_HTTP_Handler(srv))
	r.POST("/api/positions/batch-check", _PositionService_BatchCheckJobIds0_HTTP_Handler(srv))
	r.GET("/api/positions/stale", _PositionService_ListStalePositions0_HTTP_Handler(srv))
	r.GET("/api/positions/need-reply", _PositionService_ListNeedReplyPositions0_HTTP_Handler(srv))
	r.GET("/api/positions/need-resend", _PositionService_ListNeedResendPositions0_HTTP_Handler(srv))
	r.PUT("/api/position/{id}/enc-boss-id", _PositionService_UpdateEncBossId0_HTTP_Handler(srv))
	r.POST("/api/position/sync", _PositionService_SyncPosition0_HTTP_Handler(srv))
}

func _PositionService_CreatePosition0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePositionReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceCreatePosition)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePosition(ctx, req.(*CreatePositionReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateSalary0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSalaryReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateSalary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSalary(ctx, req.(*UpdateSalaryReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateStatus0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateStatusReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateStatus(ctx, req.(*UpdateStatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_MarkSkipped0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkSkippedReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceMarkSkipped)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkSkipped(ctx, req.(*MarkSkippedReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateDuties0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateDutiesReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateDuties)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateDuties(ctx, req.(*UpdateDutiesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateRequirements0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRequirementsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateRequirements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRequirements(ctx, req.(*UpdateRequirementsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateMatchRate0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMatchRateReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateMatchRate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMatchRate(ctx, req.(*UpdateMatchRateReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateNotes0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateNotesReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateNotes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateNotes(ctx, req.(*UpdateNotesReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateRecruiter0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRecruiterReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateRecruiter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRecruiter(ctx, req.(*UpdateRecruiterReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_GetPosition0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPositionReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceGetPosition)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPosition(ctx, req.(*GetPositionReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionDetailResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_GetPositionByJobId0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPositionByJobIdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceGetPositionByJobId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPositionByJobId(ctx, req.(*GetPositionByJobIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionDetailResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_ListPositions0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPositionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceListPositions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPositions(ctx, req.(*ListPositionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPositionsResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_CheckJobId0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckJobIdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceCheckJobId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckJobId(ctx, req.(*CheckJobIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckJobIdResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_BatchCheckJobIds0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BatchCheckJobIdsReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceBatchCheckJobIds)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BatchCheckJobIds(ctx, req.(*BatchCheckJobIdsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BatchCheckJobIdsResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_ListStalePositions0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStalePositionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceListStalePositions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStalePositions(ctx, req.(*ListStalePositionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPositionsResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_ListNeedReplyPositions0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNeedReplyPositionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceListNeedReplyPositions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNeedReplyPositions(ctx, req.(*ListNeedReplyPositionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPositionsResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_ListNeedResendPositions0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNeedResendPositionsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceListNeedResendPositions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNeedResendPositions(ctx, req.(*ListNeedResendPositionsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPositionsResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_UpdateEncBossId0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEncBossIdReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceUpdateEncBossId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEncBossId(ctx, req.(*UpdateEncBossIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PositionResp)
		return ctx.Result(200, reply)
	}
}

func _PositionService_SyncPosition0_HTTP_Handler(srv PositionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncPositionReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPositionServiceSyncPosition)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncPosition(ctx, req.(*SyncPositionReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncPositionResp)
		return ctx.Result(200, reply)
	}
}

type PositionServiceHTTPClient interface {
	// BatchCheckJobIds Batch check multiple jobIds at once — for dedup after loading full search results
	BatchCheckJobIds(ctx context.Context, req *BatchCheckJobIdsReq, opts ...http.CallOption) (rsp *BatchCheckJobIdsResp, err error)
	CheckJobId(ctx context.Context, req *CheckJobIdReq, opts ...http.CallOption) (rsp *CheckJobIdResp, err error)
	CreatePosition(ctx context.Context, req *CreatePositionReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	GetPosition(ctx context.Context, req *GetPositionReq, opts ...http.CallOption) (rsp *PositionDetailResp, err error)
	GetPositionByJobId(ctx context.Context, req *GetPositionByJobIdReq, opts ...http.CallOption) (rsp *PositionDetailResp, err error)
	// ListNeedReplyPositions Find positions where last message is from recruiter (we need to reply)
	ListNeedReplyPositions(ctx context.Context, req *ListNeedReplyPositionsReq, opts ...http.CallOption) (rsp *ListPositionsResp, err error)
	// ListNeedResendPositions Find positions that need resume resend (last resume != given version)
	ListNeedResendPositions(ctx context.Context, req *ListNeedResendPositionsReq, opts ...http.CallOption) (rsp *ListPositionsResp, err error)
	ListPositions(ctx context.Context, req *ListPositionsReq, opts ...http.CallOption) (rsp *ListPositionsResp, err error)
	// ListStalePositions Find positions not contacted in the last N hours — for follow-up
	ListStalePositions(ctx context.Context, req *ListStalePositionsReq, opts ...http.CallOption) (rsp *ListPositionsResp, err error)
	MarkSkipped(ctx context.Context, req *MarkSkippedReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	// SyncPosition Full sync — upsert position + replace matchItems + replace chat messages in one call
	SyncPosition(ctx context.Context, req *SyncPositionReq, opts ...http.CallOption) (rsp *SyncPositionResp, err error)
	UpdateDuties(ctx context.Context, req *UpdateDutiesReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	// UpdateEncBossId Update encBossId
	UpdateEncBossId(ctx context.Context, req *UpdateEncBossIdReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	UpdateMatchRate(ctx context.Context, req *UpdateMatchRateReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	UpdateNotes(ctx context.Context, req *UpdateNotesReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	UpdateRecruiter(ctx context.Context, req *UpdateRecruiterReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	UpdateRequirements(ctx context.Context, req *UpdateRequirementsReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	UpdateSalary(ctx context.Context, req *UpdateSalaryReq, opts ...http.CallOption) (rsp *PositionResp, err error)
	UpdateStatus(ctx context.Context, req *UpdateStatusReq, opts ...http.CallOption) (rsp *PositionResp, err error)
}

type PositionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPositionServiceHTTPClient(client *http.Client) PositionServiceHTTPClient {
	return &PositionServiceHTTPClientImpl{client}
}

// BatchCheckJobIds Batch check multiple jobIds at once — for dedup after loading full search results
func (c *PositionServiceHTTPClientImpl) BatchCheckJobIds(ctx context.Context, in *BatchCheckJobIdsReq, opts ...http.CallOption) (*BatchCheckJobIdsResp, error) {
	var out BatchCheckJobIdsResp
	pattern := "/api/positions/batch-check"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceBatchCheckJobIds))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) CheckJobId(ctx context.Context, in *CheckJobIdReq, opts ...http.CallOption) (*CheckJobIdResp, error) {
	var out CheckJobIdResp
	pattern := "/api/position/check/{job_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPositionServiceCheckJobId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) CreatePosition(ctx context.Context, in *CreatePositionReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceCreatePosition))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) GetPosition(ctx context.Context, in *GetPositionReq, opts ...http.CallOption) (*PositionDetailResp, error) {
	var out PositionDetailResp
	pattern := "/api/position/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPositionServiceGetPosition))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) GetPositionByJobId(ctx context.Context, in *GetPositionByJobIdReq, opts ...http.CallOption) (*PositionDetailResp, error) {
	var out PositionDetailResp
	pattern := "/api/position/job/{job_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPositionServiceGetPositionByJobId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNeedReplyPositions Find positions where last message is from recruiter (we need to reply)
func (c *PositionServiceHTTPClientImpl) ListNeedReplyPositions(ctx context.Context, in *ListNeedReplyPositionsReq, opts ...http.CallOption) (*ListPositionsResp, error) {
	var out ListPositionsResp
	pattern := "/api/positions/need-reply"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPositionServiceListNeedReplyPositions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNeedResendPositions Find positions that need resume resend (last resume != given version)
func (c *PositionServiceHTTPClientImpl) ListNeedResendPositions(ctx context.Context, in *ListNeedResendPositionsReq, opts ...http.CallOption) (*ListPositionsResp, error) {
	var out ListPositionsResp
	pattern := "/api/positions/need-resend"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPositionServiceListNeedResendPositions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) ListPositions(ctx context.Context, in *ListPositionsReq, opts ...http.CallOption) (*ListPositionsResp, error) {
	var out ListPositionsResp
	pattern := "/api/positions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPositionServiceListPositions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListStalePositions Find positions not contacted in the last N hours — for follow-up
func (c *PositionServiceHTTPClientImpl) ListStalePositions(ctx context.Context, in *ListStalePositionsReq, opts ...http.CallOption) (*ListPositionsResp, error) {
	var out ListPositionsResp
	pattern := "/api/positions/stale"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPositionServiceListStalePositions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) MarkSkipped(ctx context.Context, in *MarkSkippedReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/skip"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceMarkSkipped))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SyncPosition Full sync — upsert position + replace matchItems + replace chat messages in one call
func (c *PositionServiceHTTPClientImpl) SyncPosition(ctx context.Context, in *SyncPositionReq, opts ...http.CallOption) (*SyncPositionResp, error) {
	var out SyncPositionResp
	pattern := "/api/position/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceSyncPosition))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) UpdateDuties(ctx context.Context, in *UpdateDutiesReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/duties"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateDuties))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateEncBossId Update encBossId
func (c *PositionServiceHTTPClientImpl) UpdateEncBossId(ctx context.Context, in *UpdateEncBossIdReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/enc-boss-id"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateEncBossId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) UpdateMatchRate(ctx context.Context, in *UpdateMatchRateReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/match-rate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateMatchRate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) UpdateNotes(ctx context.Context, in *UpdateNotesReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/notes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateNotes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) UpdateRecruiter(ctx context.Context, in *UpdateRecruiterReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/recruiter"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateRecruiter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) UpdateRequirements(ctx context.Context, in *UpdateRequirementsReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/requirements"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateRequirements))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) UpdateSalary(ctx context.Context, in *UpdateSalaryReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/salary"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateSalary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PositionServiceHTTPClientImpl) UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...http.CallOption) (*PositionResp, error) {
	var out PositionResp
	pattern := "/api/position/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPositionServiceUpdateStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
