// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: zhipin/reason_enum.proto

package zhipin

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNKNOWN                 ErrorReason = 0
	ErrorReason_BAD_PARAM               ErrorReason = 40000
	ErrorReason_INVALID_JOB_ID          ErrorReason = 40001
	ErrorReason_MISSING_FIELD           ErrorReason = 40002
	ErrorReason_POSITION_NOT_FOUND      ErrorReason = 40400
	ErrorReason_BLACKLIST_NOT_FOUND     ErrorReason = 40401
	ErrorReason_SERVER_ERROR            ErrorReason = 50000
	ErrorReason_DB_ERROR                ErrorReason = 50001
	ErrorReason_TX_ERROR                ErrorReason = 50002
	ErrorReason_POSITION_CREATE_FAILURE ErrorReason = 50003
	ErrorReason_DUPLICATE_JOB_ID        ErrorReason = 50004
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:     "UNKNOWN",
		40000: "BAD_PARAM",
		40001: "INVALID_JOB_ID",
		40002: "MISSING_FIELD",
		40400: "POSITION_NOT_FOUND",
		40401: "BLACKLIST_NOT_FOUND",
		50000: "SERVER_ERROR",
		50001: "DB_ERROR",
		50002: "TX_ERROR",
		50003: "POSITION_CREATE_FAILURE",
		50004: "DUPLICATE_JOB_ID",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":                 0,
		"BAD_PARAM":               40000,
		"INVALID_JOB_ID":          40001,
		"MISSING_FIELD":           40002,
		"POSITION_NOT_FOUND":      40400,
		"BLACKLIST_NOT_FOUND":     40401,
		"SERVER_ERROR":            50000,
		"DB_ERROR":                50001,
		"TX_ERROR":                50002,
		"POSITION_CREATE_FAILURE": 50003,
		"DUPLICATE_JOB_ID":        50004,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_zhipin_reason_enum_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_zhipin_reason_enum_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_zhipin_reason_enum_proto_rawDescGZIP(), []int{0}
}

var File_zhipin_reason_enum_proto protoreflect.FileDescriptor

const file_zhipin_reason_enum_proto_rawDesc = "" +
	"\n" +
	"\x18zhipin/reason_enum.proto\x12\n" +
	"api.zhipin\x1a\x13errors/errors.proto*\xbe\x02\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x15\n" +
	"\tBAD_PARAM\x10\xc0\xb8\x02\x1a\x04\xa8E\x90\x03\x12\x1a\n" +
	"\x0eINVALID_JOB_ID\x10\xc1\xb8\x02\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\rMISSING_FIELD\x10¸\x02\x1a\x04\xa8E\x90\x03\x12\x1e\n" +
	"\x12POSITION_NOT_FOUND\x10л\x02\x1a\x04\xa8E\x94\x03\x12\x1f\n" +
	"\x13BLACKLIST_NOT_FOUND\x10ѻ\x02\x1a\x04\xa8E\x94\x03\x12\x18\n" +
	"\fSERVER_ERROR\x10І\x03\x1a\x04\xa8E\xf4\x03\x12\x14\n" +
	"\bDB_ERROR\x10ц\x03\x1a\x04\xa8E\xf4\x03\x12\x14\n" +
	"\bTX_ERROR\x10҆\x03\x1a\x04\xa8E\xf4\x03\x12#\n" +
	"\x17POSITION_CREATE_FAILURE\x10ӆ\x03\x1a\x04\xa8E\xf4\x03\x12\x1c\n" +
	"\x10DUPLICATE_JOB_ID\x10Ԇ\x03\x1a\x04\xa8E\x99\x03\x1a\x04\xa0E\xf4\x03BIZGgithub.com/yylego/smart-employee-zhipin/zhipin-kratos/api/zhipin;zhipinb\x06proto3"

var (
	file_zhipin_reason_enum_proto_rawDescOnce sync.Once
	file_zhipin_reason_enum_proto_rawDescData []byte
)

func file_zhipin_reason_enum_proto_rawDescGZIP() []byte {
	file_zhipin_reason_enum_proto_rawDescOnce.Do(func() {
		file_zhipin_reason_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhipin_reason_enum_proto_rawDesc), len(file_zhipin_reason_enum_proto_rawDesc)))
	})
	return file_zhipin_reason_enum_proto_rawDescData
}

var file_zhipin_reason_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zhipin_reason_enum_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.zhipin.ErrorReason
}
var file_zhipin_reason_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zhipin_reason_enum_proto_init() }
func file_zhipin_reason_enum_proto_init() {
	if File_zhipin_reason_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhipin_reason_enum_proto_rawDesc), len(file_zhipin_reason_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zhipin_reason_enum_proto_goTypes,
		DependencyIndexes: file_zhipin_reason_enum_proto_depIdxs,
		EnumInfos:         file_zhipin_reason_enum_proto_enumTypes,
	}.Build()
	File_zhipin_reason_enum_proto = out.File
	file_zhipin_reason_enum_proto_goTypes = nil
	file_zhipin_reason_enum_proto_depIdxs = nil
}
