// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: zhipin/requirement_item.proto

package zhipin

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchStatus int32

const (
	MatchStatus_MATCH_STATUS_UNKNOWN MatchStatus = 0
	MatchStatus_MATCH_STATUS_MATCHED MatchStatus = 1
	MatchStatus_MATCH_STATUS_PARTIAL MatchStatus = 2
	MatchStatus_MATCH_STATUS_MISSING MatchStatus = 3
)

// Enum value maps for MatchStatus.
var (
	MatchStatus_name = map[int32]string{
		0: "MATCH_STATUS_UNKNOWN",
		1: "MATCH_STATUS_MATCHED",
		2: "MATCH_STATUS_PARTIAL",
		3: "MATCH_STATUS_MISSING",
	}
	MatchStatus_value = map[string]int32{
		"MATCH_STATUS_UNKNOWN": 0,
		"MATCH_STATUS_MATCHED": 1,
		"MATCH_STATUS_PARTIAL": 2,
		"MATCH_STATUS_MISSING": 3,
	}
)

func (x MatchStatus) Enum() *MatchStatus {
	p := new(MatchStatus)
	*p = x
	return p
}

func (x MatchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_zhipin_requirement_item_proto_enumTypes[0].Descriptor()
}

func (MatchStatus) Type() protoreflect.EnumType {
	return &file_zhipin_requirement_item_proto_enumTypes[0]
}

func (x MatchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchStatus.Descriptor instead.
func (MatchStatus) EnumDescriptor() ([]byte, []int) {
	return file_zhipin_requirement_item_proto_rawDescGZIP(), []int{0}
}

type RequirementItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requirement   string                 `protobuf:"bytes,1,opt,name=requirement,proto3" json:"requirement,omitempty"`
	MatchStatus   int32                  `protobuf:"varint,2,opt,name=match_status,json=matchStatus,proto3" json:"match_status,omitempty"`
	ResumePoint   string                 `protobuf:"bytes,3,opt,name=resume_point,json=resumePoint,proto3" json:"resume_point,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	SortIndex     int32                  `protobuf:"varint,5,opt,name=sort_index,json=sortIndex,proto3" json:"sort_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequirementItemInput) Reset() {
	*x = RequirementItemInput{}
	mi := &file_zhipin_requirement_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequirementItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequirementItemInput) ProtoMessage() {}

func (x *RequirementItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_requirement_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequirementItemInput.ProtoReflect.Descriptor instead.
func (*RequirementItemInput) Descriptor() ([]byte, []int) {
	return file_zhipin_requirement_item_proto_rawDescGZIP(), []int{0}
}

func (x *RequirementItemInput) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *RequirementItemInput) GetMatchStatus() int32 {
	if x != nil {
		return x.MatchStatus
	}
	return 0
}

func (x *RequirementItemInput) GetResumePoint() string {
	if x != nil {
		return x.ResumePoint
	}
	return ""
}

func (x *RequirementItemInput) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RequirementItemInput) GetSortIndex() int32 {
	if x != nil {
		return x.SortIndex
	}
	return 0
}

type SetRequirementItemsReq struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	PositionId    uint64                  `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Items         []*RequirementItemInput `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequirementItemsReq) Reset() {
	*x = SetRequirementItemsReq{}
	mi := &file_zhipin_requirement_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequirementItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequirementItemsReq) ProtoMessage() {}

func (x *SetRequirementItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_requirement_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequirementItemsReq.ProtoReflect.Descriptor instead.
func (*SetRequirementItemsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_requirement_item_proto_rawDescGZIP(), []int{1}
}

func (x *SetRequirementItemsReq) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *SetRequirementItemsReq) GetItems() []*RequirementItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetRequirementItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequirementItemsResp) Reset() {
	*x = SetRequirementItemsResp{}
	mi := &file_zhipin_requirement_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequirementItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequirementItemsResp) ProtoMessage() {}

func (x *SetRequirementItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_requirement_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequirementItemsResp.ProtoReflect.Descriptor instead.
func (*SetRequirementItemsResp) Descriptor() ([]byte, []int) {
	return file_zhipin_requirement_item_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequirementItemsResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListRequirementItemsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionId    uint64                 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequirementItemsReq) Reset() {
	*x = ListRequirementItemsReq{}
	mi := &file_zhipin_requirement_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequirementItemsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequirementItemsReq) ProtoMessage() {}

func (x *ListRequirementItemsReq) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_requirement_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequirementItemsReq.ProtoReflect.Descriptor instead.
func (*ListRequirementItemsReq) Descriptor() ([]byte, []int) {
	return file_zhipin_requirement_item_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequirementItemsReq) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

type RequirementItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PositionId    uint64                 `protobuf:"varint,2,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Requirement   string                 `protobuf:"bytes,3,opt,name=requirement,proto3" json:"requirement,omitempty"`
	MatchStatus   int32                  `protobuf:"varint,4,opt,name=match_status,json=matchStatus,proto3" json:"match_status,omitempty"`
	ResumePoint   string                 `protobuf:"bytes,5,opt,name=resume_point,json=resumePoint,proto3" json:"resume_point,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	SortIndex     int32                  `protobuf:"varint,7,opt,name=sort_index,json=sortIndex,proto3" json:"sort_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequirementItemResp) Reset() {
	*x = RequirementItemResp{}
	mi := &file_zhipin_requirement_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequirementItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequirementItemResp) ProtoMessage() {}

func (x *RequirementItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_requirement_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequirementItemResp.ProtoReflect.Descriptor instead.
func (*RequirementItemResp) Descriptor() ([]byte, []int) {
	return file_zhipin_requirement_item_proto_rawDescGZIP(), []int{4}
}

func (x *RequirementItemResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequirementItemResp) GetPositionId() uint64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *RequirementItemResp) GetRequirement() string {
	if x != nil {
		return x.Requirement
	}
	return ""
}

func (x *RequirementItemResp) GetMatchStatus() int32 {
	if x != nil {
		return x.MatchStatus
	}
	return 0
}

func (x *RequirementItemResp) GetResumePoint() string {
	if x != nil {
		return x.ResumePoint
	}
	return ""
}

func (x *RequirementItemResp) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RequirementItemResp) GetSortIndex() int32 {
	if x != nil {
		return x.SortIndex
	}
	return 0
}

type ListRequirementItemsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RequirementItemResp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequirementItemsResp) Reset() {
	*x = ListRequirementItemsResp{}
	mi := &file_zhipin_requirement_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequirementItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequirementItemsResp) ProtoMessage() {}

func (x *ListRequirementItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_zhipin_requirement_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequirementItemsResp.ProtoReflect.Descriptor instead.
func (*ListRequirementItemsResp) Descriptor() ([]byte, []int) {
	return file_zhipin_requirement_item_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequirementItemsResp) GetItems() []*RequirementItemResp {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_zhipin_requirement_item_proto protoreflect.FileDescriptor

const file_zhipin_requirement_item_proto_rawDesc = "" +
	"\n" +
	"\x1dzhipin/requirement_item.proto\x12\n" +
	"api.zhipin\x1a\x1cgoogle/api/annotations.proto\"\xb5\x01\n" +
	"\x14RequirementItemInput\x12 \n" +
	"\vrequirement\x18\x01 \x01(\tR\vrequirement\x12!\n" +
	"\fmatch_status\x18\x02 \x01(\x05R\vmatchStatus\x12!\n" +
	"\fresume_point\x18\x03 \x01(\tR\vresumePoint\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"sort_index\x18\x05 \x01(\x05R\tsortIndex\"q\n" +
	"\x16SetRequirementItemsReq\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x04R\n" +
	"positionId\x126\n" +
	"\x05items\x18\x02 \x03(\v2 .api.zhipin.RequirementItemInputR\x05items\"/\n" +
	"\x17SetRequirementItemsResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\":\n" +
	"\x17ListRequirementItemsReq\x12\x1f\n" +
	"\vposition_id\x18\x01 \x01(\x04R\n" +
	"positionId\"\xe5\x01\n" +
	"\x13RequirementItemResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\vposition_id\x18\x02 \x01(\x04R\n" +
	"positionId\x12 \n" +
	"\vrequirement\x18\x03 \x01(\tR\vrequirement\x12!\n" +
	"\fmatch_status\x18\x04 \x01(\x05R\vmatchStatus\x12!\n" +
	"\fresume_point\x18\x05 \x01(\tR\vresumePoint\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"sort_index\x18\a \x01(\x05R\tsortIndex\"Q\n" +
	"\x18ListRequirementItemsResp\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.api.zhipin.RequirementItemRespR\x05items*u\n" +
	"\vMatchStatus\x12\x18\n" +
	"\x14MATCH_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14MATCH_STATUS_MATCHED\x10\x01\x12\x18\n" +
	"\x14MATCH_STATUS_PARTIAL\x10\x02\x12\x18\n" +
	"\x14MATCH_STATUS_MISSING\x10\x032\xce\x02\n" +
	"\x16RequirementItemService\x12\x98\x01\n" +
	"\x13SetRequirementItems\x12\".api.zhipin.SetRequirementItemsReq\x1a#.api.zhipin.SetRequirementItemsResp\"8\x82\xd3\xe4\x93\x022:\x01*\"-/api/position/{position_id}/requirement-items\x12\x98\x01\n" +
	"\x14ListRequirementItems\x12#.api.zhipin.ListRequirementItemsReq\x1a$.api.zhipin.ListRequirementItemsResp\"5\x82\xd3\xe4\x93\x02/\x12-/api/position/{position_id}/requirement-itemsBIZGgithub.com/yylego/smart-employee-zhipin/zhipin-kratos/api/zhipin;zhipinb\x06proto3"

var (
	file_zhipin_requirement_item_proto_rawDescOnce sync.Once
	file_zhipin_requirement_item_proto_rawDescData []byte
)

func file_zhipin_requirement_item_proto_rawDescGZIP() []byte {
	file_zhipin_requirement_item_proto_rawDescOnce.Do(func() {
		file_zhipin_requirement_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhipin_requirement_item_proto_rawDesc), len(file_zhipin_requirement_item_proto_rawDesc)))
	})
	return file_zhipin_requirement_item_proto_rawDescData
}

var file_zhipin_requirement_item_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zhipin_requirement_item_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zhipin_requirement_item_proto_goTypes = []any{
	(MatchStatus)(0),                 // 0: api.zhipin.MatchStatus
	(*RequirementItemInput)(nil),     // 1: api.zhipin.RequirementItemInput
	(*SetRequirementItemsReq)(nil),   // 2: api.zhipin.SetRequirementItemsReq
	(*SetRequirementItemsResp)(nil),  // 3: api.zhipin.SetRequirementItemsResp
	(*ListRequirementItemsReq)(nil),  // 4: api.zhipin.ListRequirementItemsReq
	(*RequirementItemResp)(nil),      // 5: api.zhipin.RequirementItemResp
	(*ListRequirementItemsResp)(nil), // 6: api.zhipin.ListRequirementItemsResp
}
var file_zhipin_requirement_item_proto_depIdxs = []int32{
	1, // 0: api.zhipin.SetRequirementItemsReq.items:type_name -> api.zhipin.RequirementItemInput
	5, // 1: api.zhipin.ListRequirementItemsResp.items:type_name -> api.zhipin.RequirementItemResp
	2, // 2: api.zhipin.RequirementItemService.SetRequirementItems:input_type -> api.zhipin.SetRequirementItemsReq
	4, // 3: api.zhipin.RequirementItemService.ListRequirementItems:input_type -> api.zhipin.ListRequirementItemsReq
	3, // 4: api.zhipin.RequirementItemService.SetRequirementItems:output_type -> api.zhipin.SetRequirementItemsResp
	6, // 5: api.zhipin.RequirementItemService.ListRequirementItems:output_type -> api.zhipin.ListRequirementItemsResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zhipin_requirement_item_proto_init() }
func file_zhipin_requirement_item_proto_init() {
	if File_zhipin_requirement_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhipin_requirement_item_proto_rawDesc), len(file_zhipin_requirement_item_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhipin_requirement_item_proto_goTypes,
		DependencyIndexes: file_zhipin_requirement_item_proto_depIdxs,
		EnumInfos:         file_zhipin_requirement_item_proto_enumTypes,
		MessageInfos:      file_zhipin_requirement_item_proto_msgTypes,
	}.Build()
	File_zhipin_requirement_item_proto = out.File
	file_zhipin_requirement_item_proto_goTypes = nil
	file_zhipin_requirement_item_proto_depIdxs = nil
}
