// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: zhipin/requirement_item.proto

package zhipin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequirementItemService_SetRequirementItems_FullMethodName  = "/api.zhipin.RequirementItemService/SetRequirementItems"
	RequirementItemService_ListRequirementItems_FullMethodName = "/api.zhipin.RequirementItemService/ListRequirementItems"
)

// RequirementItemServiceClient is the client API for RequirementItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RequirementItemService — per-requirement match analysis
type RequirementItemServiceClient interface {
	SetRequirementItems(ctx context.Context, in *SetRequirementItemsReq, opts ...grpc.CallOption) (*SetRequirementItemsResp, error)
	ListRequirementItems(ctx context.Context, in *ListRequirementItemsReq, opts ...grpc.CallOption) (*ListRequirementItemsResp, error)
}

type requirementItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequirementItemServiceClient(cc grpc.ClientConnInterface) RequirementItemServiceClient {
	return &requirementItemServiceClient{cc}
}

func (c *requirementItemServiceClient) SetRequirementItems(ctx context.Context, in *SetRequirementItemsReq, opts ...grpc.CallOption) (*SetRequirementItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRequirementItemsResp)
	err := c.cc.Invoke(ctx, RequirementItemService_SetRequirementItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requirementItemServiceClient) ListRequirementItems(ctx context.Context, in *ListRequirementItemsReq, opts ...grpc.CallOption) (*ListRequirementItemsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRequirementItemsResp)
	err := c.cc.Invoke(ctx, RequirementItemService_ListRequirementItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequirementItemServiceServer is the server API for RequirementItemService service.
// All implementations must embed UnimplementedRequirementItemServiceServer
// for forward compatibility.
//
// RequirementItemService — per-requirement match analysis
type RequirementItemServiceServer interface {
	SetRequirementItems(context.Context, *SetRequirementItemsReq) (*SetRequirementItemsResp, error)
	ListRequirementItems(context.Context, *ListRequirementItemsReq) (*ListRequirementItemsResp, error)
	mustEmbedUnimplementedRequirementItemServiceServer()
}

// UnimplementedRequirementItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequirementItemServiceServer struct{}

func (UnimplementedRequirementItemServiceServer) SetRequirementItems(context.Context, *SetRequirementItemsReq) (*SetRequirementItemsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRequirementItems not implemented")
}
func (UnimplementedRequirementItemServiceServer) ListRequirementItems(context.Context, *ListRequirementItemsReq) (*ListRequirementItemsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRequirementItems not implemented")
}
func (UnimplementedRequirementItemServiceServer) mustEmbedUnimplementedRequirementItemServiceServer() {
}
func (UnimplementedRequirementItemServiceServer) testEmbeddedByValue() {}

// UnsafeRequirementItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequirementItemServiceServer will
// result in compilation errors.
type UnsafeRequirementItemServiceServer interface {
	mustEmbedUnimplementedRequirementItemServiceServer()
}

func RegisterRequirementItemServiceServer(s grpc.ServiceRegistrar, srv RequirementItemServiceServer) {
	// If the following call panics, it indicates UnimplementedRequirementItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequirementItemService_ServiceDesc, srv)
}

func _RequirementItemService_SetRequirementItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequirementItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementItemServiceServer).SetRequirementItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementItemService_SetRequirementItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementItemServiceServer).SetRequirementItems(ctx, req.(*SetRequirementItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequirementItemService_ListRequirementItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequirementItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequirementItemServiceServer).ListRequirementItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequirementItemService_ListRequirementItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequirementItemServiceServer).ListRequirementItems(ctx, req.(*ListRequirementItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RequirementItemService_ServiceDesc is the grpc.ServiceDesc for RequirementItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequirementItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.zhipin.RequirementItemService",
	HandlerType: (*RequirementItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRequirementItems",
			Handler:    _RequirementItemService_SetRequirementItems_Handler,
		},
		{
			MethodName: "ListRequirementItems",
			Handler:    _RequirementItemService_ListRequirementItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhipin/requirement_item.proto",
}
