// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: admin/admin.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_ListTodayPositions_FullMethodName = "/api.admin.AdminService/ListTodayPositions"
	AdminService_ListAllPositions_FullMethodName   = "/api.admin.AdminService/ListAllPositions"
	AdminService_GetPositionDetail_FullMethodName  = "/api.admin.AdminService/GetPositionDetail"
	AdminService_GetStats_FullMethodName           = "/api.admin.AdminService/GetStats"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService — admin dashboard queries, separate from AI-facing APIs
type AdminServiceClient interface {
	// Today's positions — most important for the admin to see progress
	ListTodayPositions(ctx context.Context, in *ListTodayPositionsReq, opts ...grpc.CallOption) (*AdminPositionListResp, error)
	// All positions with pagination and status filter
	ListAllPositions(ctx context.Context, in *ListAllPositionsReq, opts ...grpc.CallOption) (*AdminPositionListResp, error)
	// Position detail with match items and communications
	GetPositionDetail(ctx context.Context, in *GetPositionDetailReq, opts ...grpc.CallOption) (*AdminPositionDetailResp, error)
	// Stats overview — count by status
	GetStats(ctx context.Context, in *GetStatsReq, opts ...grpc.CallOption) (*GetStatsResp, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ListTodayPositions(ctx context.Context, in *ListTodayPositionsReq, opts ...grpc.CallOption) (*AdminPositionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPositionListResp)
	err := c.cc.Invoke(ctx, AdminService_ListTodayPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListAllPositions(ctx context.Context, in *ListAllPositionsReq, opts ...grpc.CallOption) (*AdminPositionListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPositionListResp)
	err := c.cc.Invoke(ctx, AdminService_ListAllPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetPositionDetail(ctx context.Context, in *GetPositionDetailReq, opts ...grpc.CallOption) (*AdminPositionDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminPositionDetailResp)
	err := c.cc.Invoke(ctx, AdminService_GetPositionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetStats(ctx context.Context, in *GetStatsReq, opts ...grpc.CallOption) (*GetStatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResp)
	err := c.cc.Invoke(ctx, AdminService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService — admin dashboard queries, separate from AI-facing APIs
type AdminServiceServer interface {
	// Today's positions — most important for the admin to see progress
	ListTodayPositions(context.Context, *ListTodayPositionsReq) (*AdminPositionListResp, error)
	// All positions with pagination and status filter
	ListAllPositions(context.Context, *ListAllPositionsReq) (*AdminPositionListResp, error)
	// Position detail with match items and communications
	GetPositionDetail(context.Context, *GetPositionDetailReq) (*AdminPositionDetailResp, error)
	// Stats overview — count by status
	GetStats(context.Context, *GetStatsReq) (*GetStatsResp, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ListTodayPositions(context.Context, *ListTodayPositionsReq) (*AdminPositionListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTodayPositions not implemented")
}
func (UnimplementedAdminServiceServer) ListAllPositions(context.Context, *ListAllPositionsReq) (*AdminPositionListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAllPositions not implemented")
}
func (UnimplementedAdminServiceServer) GetPositionDetail(context.Context, *GetPositionDetailReq) (*AdminPositionDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositionDetail not implemented")
}
func (UnimplementedAdminServiceServer) GetStats(context.Context, *GetStatsReq) (*GetStatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ListTodayPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodayPositionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTodayPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListTodayPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTodayPositions(ctx, req.(*ListTodayPositionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListAllPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllPositionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListAllPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListAllPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListAllPositions(ctx, req.(*ListAllPositionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetPositionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPositionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPositionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPositionDetail(ctx, req.(*GetPositionDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetStats(ctx, req.(*GetStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.admin.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTodayPositions",
			Handler:    _AdminService_ListTodayPositions_Handler,
		},
		{
			MethodName: "ListAllPositions",
			Handler:    _AdminService_ListAllPositions_Handler,
		},
		{
			MethodName: "GetPositionDetail",
			Handler:    _AdminService_GetPositionDetail_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _AdminService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/admin.proto",
}
