/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter ts_nocheck,eslint_disable,long_type_string
// @generated from protobuf file "zhipin/communication.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message api.zhipin.ChatMessage
 */
export interface ChatMessage {
    /**
     * @generated from protobuf field: int32 direction = 1
     */
    direction: number; // 0=me 1=them
    /**
     * @generated from protobuf field: string content = 2
     */
    content: string; // message text
    /**
     * @generated from protobuf field: int64 timestamp = 3
     */
    timestamp: string; // unix seconds
    /**
     * @generated from protobuf field: bool is_resume = 4
     */
    isResume: boolean; // is this a resume message
    /**
     * @generated from protobuf field: string resume_version = 5
     */
    resumeVersion: string; // resume filename if is_resume=true
}
/**
 * @generated from protobuf message api.zhipin.SyncChatReq
 */
export interface SyncChatReq {
    /**
     * @generated from protobuf field: string job_id = 1
     */
    jobId: string;
    /**
     * @generated from protobuf field: repeated api.zhipin.ChatMessage messages = 2
     */
    messages: ChatMessage[];
}
/**
 * @generated from protobuf message api.zhipin.SyncChatResp
 */
export interface SyncChatResp {
    /**
     * @generated from protobuf field: int64 last_comm_at = 1
     */
    lastCommAt: string; // extracted from messages
    /**
     * @generated from protobuf field: int32 last_comm_dir = 2
     */
    lastCommDir: number; // extracted from messages
    /**
     * @generated from protobuf field: string last_resume = 3
     */
    lastResume: string; // extracted from messages
    /**
     * @generated from protobuf field: int32 message_count = 4
     */
    messageCount: number;
}
/**
 * @generated from protobuf message api.zhipin.GetChatReq
 */
export interface GetChatReq {
    /**
     * @generated from protobuf field: string job_id = 1
     */
    jobId: string;
}
/**
 * @generated from protobuf message api.zhipin.GetChatResp
 */
export interface GetChatResp {
    /**
     * @generated from protobuf field: repeated api.zhipin.ChatMessage messages = 1
     */
    messages: ChatMessage[];
}
// @generated message type with reflection information, may provide speed optimized methods
class ChatMessage$Type extends MessageType<ChatMessage> {
    constructor() {
        super("api.zhipin.ChatMessage", [
            { no: 1, name: "direction", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "is_resume", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "resume_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ChatMessage>): ChatMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.direction = 0;
        message.content = "";
        message.timestamp = "0";
        message.isResume = false;
        message.resumeVersion = "";
        if (value !== undefined)
            reflectionMergePartial<ChatMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChatMessage): ChatMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 direction */ 1:
                    message.direction = reader.int32();
                    break;
                case /* string content */ 2:
                    message.content = reader.string();
                    break;
                case /* int64 timestamp */ 3:
                    message.timestamp = reader.int64().toString();
                    break;
                case /* bool is_resume */ 4:
                    message.isResume = reader.bool();
                    break;
                case /* string resume_version */ 5:
                    message.resumeVersion = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChatMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 direction = 1; */
        if (message.direction !== 0)
            writer.tag(1, WireType.Varint).int32(message.direction);
        /* string content = 2; */
        if (message.content !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.content);
        /* int64 timestamp = 3; */
        if (message.timestamp !== "0")
            writer.tag(3, WireType.Varint).int64(message.timestamp);
        /* bool is_resume = 4; */
        if (message.isResume !== false)
            writer.tag(4, WireType.Varint).bool(message.isResume);
        /* string resume_version = 5; */
        if (message.resumeVersion !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.resumeVersion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.ChatMessage
 */
export const ChatMessage = new ChatMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncChatReq$Type extends MessageType<SyncChatReq> {
    constructor() {
        super("api.zhipin.SyncChatReq", [
            { no: 1, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "messages", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ChatMessage }
        ]);
    }
    create(value?: PartialMessage<SyncChatReq>): SyncChatReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = "";
        message.messages = [];
        if (value !== undefined)
            reflectionMergePartial<SyncChatReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SyncChatReq): SyncChatReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string job_id */ 1:
                    message.jobId = reader.string();
                    break;
                case /* repeated api.zhipin.ChatMessage messages */ 2:
                    message.messages.push(ChatMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SyncChatReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string job_id = 1; */
        if (message.jobId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.jobId);
        /* repeated api.zhipin.ChatMessage messages = 2; */
        for (let i = 0; i < message.messages.length; i++)
            ChatMessage.internalBinaryWrite(message.messages[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.SyncChatReq
 */
export const SyncChatReq = new SyncChatReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SyncChatResp$Type extends MessageType<SyncChatResp> {
    constructor() {
        super("api.zhipin.SyncChatResp", [
            { no: 1, name: "last_comm_at", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "last_comm_dir", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "last_resume", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "message_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SyncChatResp>): SyncChatResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.lastCommAt = "0";
        message.lastCommDir = 0;
        message.lastResume = "";
        message.messageCount = 0;
        if (value !== undefined)
            reflectionMergePartial<SyncChatResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SyncChatResp): SyncChatResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 last_comm_at */ 1:
                    message.lastCommAt = reader.int64().toString();
                    break;
                case /* int32 last_comm_dir */ 2:
                    message.lastCommDir = reader.int32();
                    break;
                case /* string last_resume */ 3:
                    message.lastResume = reader.string();
                    break;
                case /* int32 message_count */ 4:
                    message.messageCount = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SyncChatResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 last_comm_at = 1; */
        if (message.lastCommAt !== "0")
            writer.tag(1, WireType.Varint).int64(message.lastCommAt);
        /* int32 last_comm_dir = 2; */
        if (message.lastCommDir !== 0)
            writer.tag(2, WireType.Varint).int32(message.lastCommDir);
        /* string last_resume = 3; */
        if (message.lastResume !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.lastResume);
        /* int32 message_count = 4; */
        if (message.messageCount !== 0)
            writer.tag(4, WireType.Varint).int32(message.messageCount);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.SyncChatResp
 */
export const SyncChatResp = new SyncChatResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChatReq$Type extends MessageType<GetChatReq> {
    constructor() {
        super("api.zhipin.GetChatReq", [
            { no: 1, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetChatReq>): GetChatReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = "";
        if (value !== undefined)
            reflectionMergePartial<GetChatReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChatReq): GetChatReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string job_id */ 1:
                    message.jobId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChatReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string job_id = 1; */
        if (message.jobId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.jobId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.GetChatReq
 */
export const GetChatReq = new GetChatReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetChatResp$Type extends MessageType<GetChatResp> {
    constructor() {
        super("api.zhipin.GetChatResp", [
            { no: 1, name: "messages", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ChatMessage }
        ]);
    }
    create(value?: PartialMessage<GetChatResp>): GetChatResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.messages = [];
        if (value !== undefined)
            reflectionMergePartial<GetChatResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetChatResp): GetChatResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated api.zhipin.ChatMessage messages */ 1:
                    message.messages.push(ChatMessage.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetChatResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated api.zhipin.ChatMessage messages = 1; */
        for (let i = 0; i < message.messages.length; i++)
            ChatMessage.internalBinaryWrite(message.messages[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.GetChatResp
 */
export const GetChatResp = new GetChatResp$Type();
/**
 * @generated ServiceType for protobuf service api.zhipin.CommunicationService
 */
export const CommunicationService = new ServiceType("api.zhipin.CommunicationService", [
    { name: "SyncChat", options: { "google.api.http": { post: "/api/chat/{job_id}", body: "*" } }, I: SyncChatReq, O: SyncChatResp },
    { name: "GetChat", options: { "google.api.http": { get: "/api/chat/{job_id}" } }, I: GetChatReq, O: GetChatResp }
]);
