/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter ts_nocheck,eslint_disable,long_type_string
// @generated from protobuf file "zhipin/communication.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CommunicationService } from "./communication";
import type { GetChatResp } from "./communication";
import type { GetChatReq } from "./communication";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SyncChatResp } from "./communication";
import type { SyncChatReq } from "./communication";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * CommunicationService — sync and retrieve chat records per position
 *
 * @generated from protobuf service api.zhipin.CommunicationService
 */
export interface ICommunicationServiceClient {
    /**
     * @generated from protobuf rpc: SyncChat
     */
    syncChat(input: SyncChatReq, options?: RpcOptions): GrpcToHttpPromise<SyncChatReq, SyncChatResp>;
    /**
     * @generated from protobuf rpc: GetChat
     */
    getChat(input: GetChatReq, options?: RpcOptions): GrpcToHttpPromise<GetChatReq, GetChatResp>;
}
/**
 * CommunicationService — sync and retrieve chat records per position
 *
 * @generated from protobuf service api.zhipin.CommunicationService
 */
export class CommunicationServiceClient implements ICommunicationServiceClient, ServiceInfo {
    typeName = CommunicationService.typeName;
    methods = CommunicationService.methods;
    options = CommunicationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SyncChat
     */
    syncChat(input: SyncChatReq, options?: RpcOptions): GrpcToHttpPromise<SyncChatReq, SyncChatResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<SyncChatReq, SyncChatResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetChat
     */
    getChat(input: GetChatReq, options?: RpcOptions): GrpcToHttpPromise<GetChatReq, GetChatResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<GetChatReq, GetChatResp>("unary", this._transport, method, opt, input);
    }
}
