// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "zhipin/position.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { PositionService } from "./position";
import type { UpdateEncBossIdReq } from "./position";
import type { ListNeedResendPositionsReq } from "./position";
import type { ListNeedReplyPositionsReq } from "./position";
import type { ListStalePositionsReq } from "./position";
import type { BatchCheckJobIdsResp } from "./position";
import type { BatchCheckJobIdsReq } from "./position";
import type { CheckJobIdResp } from "./position";
import type { CheckJobIdReq } from "./position";
import type { ListPositionsResp } from "./position";
import type { ListPositionsReq } from "./position";
import type { GetPositionByJobIdReq } from "./position";
import type { PositionDetailResp } from "./position";
import type { GetPositionReq } from "./position";
import type { UpdateRecruiterReq } from "./position";
import type { UpdateNotesReq } from "./position";
import type { UpdateMatchRateReq } from "./position";
import type { UpdateRequirementsReq } from "./position";
import type { UpdateDutiesReq } from "./position";
import type { MarkSkippedReq } from "./position";
import type { UpdateStatusReq } from "./position";
import type { UpdateSalaryReq } from "./position";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PositionResp } from "./position";
import type { CreatePositionReq } from "./position";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * PositionService — job position CRUD and status tracking
 *
 * @generated from protobuf service api.zhipin.PositionService
 */
export interface IPositionServiceClient {
    /**
     * @generated from protobuf rpc: CreatePosition
     */
    createPosition(input: CreatePositionReq, options?: RpcOptions): GrpcToHttpPromise<CreatePositionReq, PositionResp>;
    /**
     * @generated from protobuf rpc: UpdateSalary
     */
    updateSalary(input: UpdateSalaryReq, options?: RpcOptions): GrpcToHttpPromise<UpdateSalaryReq, PositionResp>;
    /**
     * @generated from protobuf rpc: UpdateStatus
     */
    updateStatus(input: UpdateStatusReq, options?: RpcOptions): GrpcToHttpPromise<UpdateStatusReq, PositionResp>;
    /**
     * @generated from protobuf rpc: MarkSkipped
     */
    markSkipped(input: MarkSkippedReq, options?: RpcOptions): GrpcToHttpPromise<MarkSkippedReq, PositionResp>;
    /**
     * @generated from protobuf rpc: UpdateDuties
     */
    updateDuties(input: UpdateDutiesReq, options?: RpcOptions): GrpcToHttpPromise<UpdateDutiesReq, PositionResp>;
    /**
     * @generated from protobuf rpc: UpdateRequirements
     */
    updateRequirements(input: UpdateRequirementsReq, options?: RpcOptions): GrpcToHttpPromise<UpdateRequirementsReq, PositionResp>;
    /**
     * @generated from protobuf rpc: UpdateMatchRate
     */
    updateMatchRate(input: UpdateMatchRateReq, options?: RpcOptions): GrpcToHttpPromise<UpdateMatchRateReq, PositionResp>;
    /**
     * @generated from protobuf rpc: UpdateNotes
     */
    updateNotes(input: UpdateNotesReq, options?: RpcOptions): GrpcToHttpPromise<UpdateNotesReq, PositionResp>;
    /**
     * @generated from protobuf rpc: UpdateRecruiter
     */
    updateRecruiter(input: UpdateRecruiterReq, options?: RpcOptions): GrpcToHttpPromise<UpdateRecruiterReq, PositionResp>;
    /**
     * @generated from protobuf rpc: GetPosition
     */
    getPosition(input: GetPositionReq, options?: RpcOptions): GrpcToHttpPromise<GetPositionReq, PositionDetailResp>;
    /**
     * @generated from protobuf rpc: GetPositionByJobId
     */
    getPositionByJobId(input: GetPositionByJobIdReq, options?: RpcOptions): GrpcToHttpPromise<GetPositionByJobIdReq, PositionDetailResp>;
    /**
     * @generated from protobuf rpc: ListPositions
     */
    listPositions(input: ListPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListPositionsReq, ListPositionsResp>;
    /**
     * @generated from protobuf rpc: CheckJobId
     */
    checkJobId(input: CheckJobIdReq, options?: RpcOptions): GrpcToHttpPromise<CheckJobIdReq, CheckJobIdResp>;
    /**
     * Batch check multiple jobIds at once — for dedup after loading full search results
     *
     * @generated from protobuf rpc: BatchCheckJobIds
     */
    batchCheckJobIds(input: BatchCheckJobIdsReq, options?: RpcOptions): GrpcToHttpPromise<BatchCheckJobIdsReq, BatchCheckJobIdsResp>;
    /**
     * Find positions not contacted in the last N hours — for follow-up
     *
     * @generated from protobuf rpc: ListStalePositions
     */
    listStalePositions(input: ListStalePositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListStalePositionsReq, ListPositionsResp>;
    /**
     * Find positions where last message is from recruiter (we need to reply)
     *
     * @generated from protobuf rpc: ListNeedReplyPositions
     */
    listNeedReplyPositions(input: ListNeedReplyPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListNeedReplyPositionsReq, ListPositionsResp>;
    /**
     * Find positions that need resume resend (last resume != given version)
     *
     * @generated from protobuf rpc: ListNeedResendPositions
     */
    listNeedResendPositions(input: ListNeedResendPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListNeedResendPositionsReq, ListPositionsResp>;
    /**
     * Update encBossId
     *
     * @generated from protobuf rpc: UpdateEncBossId
     */
    updateEncBossId(input: UpdateEncBossIdReq, options?: RpcOptions): GrpcToHttpPromise<UpdateEncBossIdReq, PositionResp>;
}
/**
 * PositionService — job position CRUD and status tracking
 *
 * @generated from protobuf service api.zhipin.PositionService
 */
export class PositionServiceClient implements IPositionServiceClient, ServiceInfo {
    typeName = PositionService.typeName;
    methods = PositionService.methods;
    options = PositionService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreatePosition
     */
    createPosition(input: CreatePositionReq, options?: RpcOptions): GrpcToHttpPromise<CreatePositionReq, PositionResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<CreatePositionReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSalary
     */
    updateSalary(input: UpdateSalaryReq, options?: RpcOptions): GrpcToHttpPromise<UpdateSalaryReq, PositionResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateSalaryReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateStatus
     */
    updateStatus(input: UpdateStatusReq, options?: RpcOptions): GrpcToHttpPromise<UpdateStatusReq, PositionResp> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateStatusReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: MarkSkipped
     */
    markSkipped(input: MarkSkippedReq, options?: RpcOptions): GrpcToHttpPromise<MarkSkippedReq, PositionResp> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<MarkSkippedReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateDuties
     */
    updateDuties(input: UpdateDutiesReq, options?: RpcOptions): GrpcToHttpPromise<UpdateDutiesReq, PositionResp> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateDutiesReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateRequirements
     */
    updateRequirements(input: UpdateRequirementsReq, options?: RpcOptions): GrpcToHttpPromise<UpdateRequirementsReq, PositionResp> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateRequirementsReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateMatchRate
     */
    updateMatchRate(input: UpdateMatchRateReq, options?: RpcOptions): GrpcToHttpPromise<UpdateMatchRateReq, PositionResp> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateMatchRateReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateNotes
     */
    updateNotes(input: UpdateNotesReq, options?: RpcOptions): GrpcToHttpPromise<UpdateNotesReq, PositionResp> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateNotesReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateRecruiter
     */
    updateRecruiter(input: UpdateRecruiterReq, options?: RpcOptions): GrpcToHttpPromise<UpdateRecruiterReq, PositionResp> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateRecruiterReq, PositionResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPosition
     */
    getPosition(input: GetPositionReq, options?: RpcOptions): GrpcToHttpPromise<GetPositionReq, PositionDetailResp> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<GetPositionReq, PositionDetailResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPositionByJobId
     */
    getPositionByJobId(input: GetPositionByJobIdReq, options?: RpcOptions): GrpcToHttpPromise<GetPositionByJobIdReq, PositionDetailResp> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<GetPositionByJobIdReq, PositionDetailResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPositions
     */
    listPositions(input: ListPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListPositionsReq, ListPositionsResp> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListPositionsReq, ListPositionsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CheckJobId
     */
    checkJobId(input: CheckJobIdReq, options?: RpcOptions): GrpcToHttpPromise<CheckJobIdReq, CheckJobIdResp> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<CheckJobIdReq, CheckJobIdResp>("unary", this._transport, method, opt, input);
    }
    /**
     * Batch check multiple jobIds at once — for dedup after loading full search results
     *
     * @generated from protobuf rpc: BatchCheckJobIds
     */
    batchCheckJobIds(input: BatchCheckJobIdsReq, options?: RpcOptions): GrpcToHttpPromise<BatchCheckJobIdsReq, BatchCheckJobIdsResp> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<BatchCheckJobIdsReq, BatchCheckJobIdsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * Find positions not contacted in the last N hours — for follow-up
     *
     * @generated from protobuf rpc: ListStalePositions
     */
    listStalePositions(input: ListStalePositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListStalePositionsReq, ListPositionsResp> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListStalePositionsReq, ListPositionsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * Find positions where last message is from recruiter (we need to reply)
     *
     * @generated from protobuf rpc: ListNeedReplyPositions
     */
    listNeedReplyPositions(input: ListNeedReplyPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListNeedReplyPositionsReq, ListPositionsResp> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListNeedReplyPositionsReq, ListPositionsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * Find positions that need resume resend (last resume != given version)
     *
     * @generated from protobuf rpc: ListNeedResendPositions
     */
    listNeedResendPositions(input: ListNeedResendPositionsReq, options?: RpcOptions): GrpcToHttpPromise<ListNeedResendPositionsReq, ListPositionsResp> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListNeedResendPositionsReq, ListPositionsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * Update encBossId
     *
     * @generated from protobuf rpc: UpdateEncBossId
     */
    updateEncBossId(input: UpdateEncBossIdReq, options?: RpcOptions): GrpcToHttpPromise<UpdateEncBossIdReq, PositionResp> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<UpdateEncBossIdReq, PositionResp>("unary", this._transport, method, opt, input);
    }
}
