// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "zhipin/requirement_item.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message api.zhipin.RequirementItemInput
 */
export interface RequirementItemInput {
    /**
     * @generated from protobuf field: string requirement = 1
     */
    requirement: string;
    /**
     * @generated from protobuf field: int32 match_status = 2
     */
    matchStatus: number;
    /**
     * @generated from protobuf field: string resume_point = 3
     */
    resumePoint: string;
    /**
     * @generated from protobuf field: string remark = 4
     */
    remark: string;
    /**
     * @generated from protobuf field: int32 sort_index = 5
     */
    sortIndex: number;
}
/**
 * @generated from protobuf message api.zhipin.SetRequirementItemsReq
 */
export interface SetRequirementItemsReq {
    /**
     * @generated from protobuf field: string job_id = 1
     */
    jobId: string;
    /**
     * @generated from protobuf field: repeated api.zhipin.RequirementItemInput items = 2
     */
    items: RequirementItemInput[];
}
/**
 * @generated from protobuf message api.zhipin.SetRequirementItemsResp
 */
export interface SetRequirementItemsResp {
    /**
     * @generated from protobuf field: int32 count = 1
     */
    count: number;
}
/**
 * @generated from protobuf message api.zhipin.ListRequirementItemsReq
 */
export interface ListRequirementItemsReq {
    /**
     * @generated from protobuf field: string job_id = 1
     */
    jobId: string;
}
/**
 * @generated from protobuf message api.zhipin.RequirementItemResp
 */
export interface RequirementItemResp {
    /**
     * @generated from protobuf field: uint64 id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string job_id = 2
     */
    jobId: string;
    /**
     * @generated from protobuf field: string requirement = 3
     */
    requirement: string;
    /**
     * @generated from protobuf field: int32 match_status = 4
     */
    matchStatus: number;
    /**
     * @generated from protobuf field: string resume_point = 5
     */
    resumePoint: string;
    /**
     * @generated from protobuf field: string remark = 6
     */
    remark: string;
    /**
     * @generated from protobuf field: int32 sort_index = 7
     */
    sortIndex: number;
}
/**
 * @generated from protobuf message api.zhipin.ListRequirementItemsResp
 */
export interface ListRequirementItemsResp {
    /**
     * @generated from protobuf field: repeated api.zhipin.RequirementItemResp items = 1
     */
    items: RequirementItemResp[];
}
/**
 * @generated from protobuf enum api.zhipin.MatchStatus
 */
export enum MatchStatus {
    /**
     * @generated from protobuf enum value: MATCH_STATUS_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: MATCH_STATUS_MATCHED = 1;
     */
    MATCHED = 1,
    /**
     * @generated from protobuf enum value: MATCH_STATUS_PARTIAL = 2;
     */
    PARTIAL = 2,
    /**
     * @generated from protobuf enum value: MATCH_STATUS_MISSING = 3;
     */
    MISSING = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class RequirementItemInput$Type extends MessageType<RequirementItemInput> {
    constructor() {
        super("api.zhipin.RequirementItemInput", [
            { no: 1, name: "requirement", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "match_status", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "resume_point", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "remark", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "sort_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RequirementItemInput>): RequirementItemInput {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requirement = "";
        message.matchStatus = 0;
        message.resumePoint = "";
        message.remark = "";
        message.sortIndex = 0;
        if (value !== undefined)
            reflectionMergePartial<RequirementItemInput>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequirementItemInput): RequirementItemInput {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string requirement */ 1:
                    message.requirement = reader.string();
                    break;
                case /* int32 match_status */ 2:
                    message.matchStatus = reader.int32();
                    break;
                case /* string resume_point */ 3:
                    message.resumePoint = reader.string();
                    break;
                case /* string remark */ 4:
                    message.remark = reader.string();
                    break;
                case /* int32 sort_index */ 5:
                    message.sortIndex = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequirementItemInput, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string requirement = 1; */
        if (message.requirement !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.requirement);
        /* int32 match_status = 2; */
        if (message.matchStatus !== 0)
            writer.tag(2, WireType.Varint).int32(message.matchStatus);
        /* string resume_point = 3; */
        if (message.resumePoint !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.resumePoint);
        /* string remark = 4; */
        if (message.remark !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.remark);
        /* int32 sort_index = 5; */
        if (message.sortIndex !== 0)
            writer.tag(5, WireType.Varint).int32(message.sortIndex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RequirementItemInput
 */
export const RequirementItemInput = new RequirementItemInput$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetRequirementItemsReq$Type extends MessageType<SetRequirementItemsReq> {
    constructor() {
        super("api.zhipin.SetRequirementItemsReq", [
            { no: 1, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => RequirementItemInput }
        ]);
    }
    create(value?: PartialMessage<SetRequirementItemsReq>): SetRequirementItemsReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = "";
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<SetRequirementItemsReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetRequirementItemsReq): SetRequirementItemsReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string job_id */ 1:
                    message.jobId = reader.string();
                    break;
                case /* repeated api.zhipin.RequirementItemInput items */ 2:
                    message.items.push(RequirementItemInput.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetRequirementItemsReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string job_id = 1; */
        if (message.jobId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.jobId);
        /* repeated api.zhipin.RequirementItemInput items = 2; */
        for (let i = 0; i < message.items.length; i++)
            RequirementItemInput.internalBinaryWrite(message.items[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.SetRequirementItemsReq
 */
export const SetRequirementItemsReq = new SetRequirementItemsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetRequirementItemsResp$Type extends MessageType<SetRequirementItemsResp> {
    constructor() {
        super("api.zhipin.SetRequirementItemsResp", [
            { no: 1, name: "count", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SetRequirementItemsResp>): SetRequirementItemsResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.count = 0;
        if (value !== undefined)
            reflectionMergePartial<SetRequirementItemsResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetRequirementItemsResp): SetRequirementItemsResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 count */ 1:
                    message.count = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetRequirementItemsResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 count = 1; */
        if (message.count !== 0)
            writer.tag(1, WireType.Varint).int32(message.count);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.SetRequirementItemsResp
 */
export const SetRequirementItemsResp = new SetRequirementItemsResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListRequirementItemsReq$Type extends MessageType<ListRequirementItemsReq> {
    constructor() {
        super("api.zhipin.ListRequirementItemsReq", [
            { no: 1, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListRequirementItemsReq>): ListRequirementItemsReq {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.jobId = "";
        if (value !== undefined)
            reflectionMergePartial<ListRequirementItemsReq>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListRequirementItemsReq): ListRequirementItemsReq {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string job_id */ 1:
                    message.jobId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListRequirementItemsReq, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string job_id = 1; */
        if (message.jobId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.jobId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.ListRequirementItemsReq
 */
export const ListRequirementItemsReq = new ListRequirementItemsReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RequirementItemResp$Type extends MessageType<RequirementItemResp> {
    constructor() {
        super("api.zhipin.RequirementItemResp", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "job_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "requirement", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "match_status", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "resume_point", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "remark", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "sort_index", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<RequirementItemResp>): RequirementItemResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "0";
        message.jobId = "";
        message.requirement = "";
        message.matchStatus = 0;
        message.resumePoint = "";
        message.remark = "";
        message.sortIndex = 0;
        if (value !== undefined)
            reflectionMergePartial<RequirementItemResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequirementItemResp): RequirementItemResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toString();
                    break;
                case /* string job_id */ 2:
                    message.jobId = reader.string();
                    break;
                case /* string requirement */ 3:
                    message.requirement = reader.string();
                    break;
                case /* int32 match_status */ 4:
                    message.matchStatus = reader.int32();
                    break;
                case /* string resume_point */ 5:
                    message.resumePoint = reader.string();
                    break;
                case /* string remark */ 6:
                    message.remark = reader.string();
                    break;
                case /* int32 sort_index */ 7:
                    message.sortIndex = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequirementItemResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== "0")
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* string job_id = 2; */
        if (message.jobId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.jobId);
        /* string requirement = 3; */
        if (message.requirement !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.requirement);
        /* int32 match_status = 4; */
        if (message.matchStatus !== 0)
            writer.tag(4, WireType.Varint).int32(message.matchStatus);
        /* string resume_point = 5; */
        if (message.resumePoint !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.resumePoint);
        /* string remark = 6; */
        if (message.remark !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.remark);
        /* int32 sort_index = 7; */
        if (message.sortIndex !== 0)
            writer.tag(7, WireType.Varint).int32(message.sortIndex);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.RequirementItemResp
 */
export const RequirementItemResp = new RequirementItemResp$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListRequirementItemsResp$Type extends MessageType<ListRequirementItemsResp> {
    constructor() {
        super("api.zhipin.ListRequirementItemsResp", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => RequirementItemResp }
        ]);
    }
    create(value?: PartialMessage<ListRequirementItemsResp>): ListRequirementItemsResp {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial<ListRequirementItemsResp>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListRequirementItemsResp): ListRequirementItemsResp {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated api.zhipin.RequirementItemResp items */ 1:
                    message.items.push(RequirementItemResp.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListRequirementItemsResp, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated api.zhipin.RequirementItemResp items = 1; */
        for (let i = 0; i < message.items.length; i++)
            RequirementItemResp.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.zhipin.ListRequirementItemsResp
 */
export const ListRequirementItemsResp = new ListRequirementItemsResp$Type();
/**
 * @generated ServiceType for protobuf service api.zhipin.RequirementItemService
 */
export const RequirementItemService = new ServiceType("api.zhipin.RequirementItemService", [
    { name: "SetRequirementItems", options: { "google.api.http": { post: "/api/requirement-items/{job_id}", body: "*" } }, I: SetRequirementItemsReq, O: SetRequirementItemsResp },
    { name: "ListRequirementItems", options: { "google.api.http": { get: "/api/requirement-items/{job_id}" } }, I: ListRequirementItemsReq, O: ListRequirementItemsResp }
]);
