/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter ts_nocheck,eslint_disable,long_type_string
// @generated from protobuf file "zhipin/requirement_item.proto" (package "api.zhipin", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RequirementItemService } from "./requirement_item";
import type { ListRequirementItemsResp } from "./requirement_item";
import type { ListRequirementItemsReq } from "./requirement_item";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SetRequirementItemsResp } from "./requirement_item";
import type { SetRequirementItemsReq } from "./requirement_item";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
import { executeGrpcToHttp } from '@yylego/grpc-to-http';
import type { GrpcToHttpPromise } from '@yylego/grpc-to-http';
/**
 * RequirementItemService — per-requirement match analysis
 *
 * @generated from protobuf service api.zhipin.RequirementItemService
 */
export interface IRequirementItemServiceClient {
    /**
     * @generated from protobuf rpc: SetRequirementItems
     */
    setRequirementItems(input: SetRequirementItemsReq, options?: RpcOptions): GrpcToHttpPromise<SetRequirementItemsReq, SetRequirementItemsResp>;
    /**
     * @generated from protobuf rpc: ListRequirementItems
     */
    listRequirementItems(input: ListRequirementItemsReq, options?: RpcOptions): GrpcToHttpPromise<ListRequirementItemsReq, ListRequirementItemsResp>;
}
/**
 * RequirementItemService — per-requirement match analysis
 *
 * @generated from protobuf service api.zhipin.RequirementItemService
 */
export class RequirementItemServiceClient implements IRequirementItemServiceClient, ServiceInfo {
    typeName = RequirementItemService.typeName;
    methods = RequirementItemService.methods;
    options = RequirementItemService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SetRequirementItems
     */
    setRequirementItems(input: SetRequirementItemsReq, options?: RpcOptions): GrpcToHttpPromise<SetRequirementItemsReq, SetRequirementItemsResp> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<SetRequirementItemsReq, SetRequirementItemsResp>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListRequirementItems
     */
    listRequirementItems(input: ListRequirementItemsReq, options?: RpcOptions): GrpcToHttpPromise<ListRequirementItemsReq, ListRequirementItemsResp> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return executeGrpcToHttp<ListRequirementItemsReq, ListRequirementItemsResp>("unary", this._transport, method, opt, input);
    }
}
